import{initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import{getAuth,onAuthStateChanged,signInWithEmailAndPassword}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import{getDatabase,ref,get,onValue,update,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-database.js";
import{QUESTIONS,answerLabel}from"../quiz-data.js";
import{MEDICATION_EXERCISES,STATUS_OPTIONS}from"../medication-data.js";
const config={apiKey:"AIzaSyCX6Y_ImG1YNEMY19pSSl4FxaHKqo72B3s",authDomain:"activites-procyclean.firebaseapp.com",databaseURL:"https://activites-procyclean-default-rtdb.europe-west1.firebasedatabase.app/",projectId:"activites-procyclean",storageBucket:"activites-procyclean.firebasestorage.app",messagingSenderId:"900663423725",appId:"1:900663423725:web:bc51501dcf653bfd1052e4"};
const auth=getAuth(initializeApp(config)),database=getDatabase(),$=selector=>document.querySelector(selector),EMAIL="prevention.dopage@ffc.fr";
let session,busy=false,stopSession=null,code=String(new URLSearchParams(location.search).get("session")||"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6);
$("#session-code").textContent=$("#waiting-code").textContent=code||"—";
function top(panel){["#loading-panel","#login-panel","#error-panel"].forEach(id=>$(id).hidden=$(id)!==panel);$("#content").hidden=panel!==null}
function people(){return Object.values(session?.participants||{})}
function label(value){if(value.status==="waiting")return"En attente";if(value.status==="closed")return"Terminée";if(value.status==="final")return"Transition finale";return value.phase==="medications"?"Vérification AFLD":value.phase==="medicationIntro"?"Transition":"Quiz en cours"}
function distribution(records,options){return options.map(option=>{const count=records.filter(record=>record.answer===option.id).length,percent=records.length?Math.round(count/records.length*100):0,article=document.createElement("article");article.innerHTML="<header><strong>"+option.label+"</strong><span>"+count+" · "+percent+" %</span></header><progress max='100' value='"+percent+"'></progress>";return article})}
function renderQuiz(){const index=Math.min(Number(session.currentQuestion)||0,QUESTIONS.length-1),question=QUESTIONS[index],participants=people(),records=participants.map(person=>person.quizAnswers?.[question.id]).filter(Boolean),revealed=!!session.feedbackRevealed;$("#answered").textContent=records.length;$("#question-count").textContent="QUESTION "+(index+1)+" / "+QUESTIONS.length;$("#response-rate").textContent=records.length+" réponse"+(records.length>1?"s":"")+" sur "+participants.length;$("#progress-bar").style.width=((index+1)/QUESTIONS.length*100)+"%";$("#situation").hidden=!question.situation;$("#situation").textContent=question.situation||"";$("#question").textContent=question.statement;$("#distribution").replaceChildren(...distribution(records,question.answers));$("#correction").hidden=!revealed;$("#correct-answer").textContent="Bonne réponse : "+answerLabel(question,question.correct);$("#feedback-text").textContent=question.feedback;$("#reveal").hidden=revealed;$("#next").hidden=!revealed;$("#next").textContent=index===QUESTIONS.length-1?"Passer à la vérification":"Question suivante"}
function renderMedication(){const index=Math.min(Number(session.currentMedication)||0,MEDICATION_EXERCISES.length-1),exercise=MEDICATION_EXERCISES[index],participants=people(),records=participants.map(person=>person.medicationAnswers?.[exercise.id]).filter(Boolean),revealed=!!session.medicationFeedbackRevealed;$("#answered").textContent=records.length;$("#medication-level").textContent=exercise.level+" · RECHERCHE "+(index+1)+" / "+MEDICATION_EXERCISES.length;$("#medication-response-rate").textContent=records.length+" réponse"+(records.length>1?"s":"")+" sur "+participants.length;$("#medication-progress").style.width=((index+1)/MEDICATION_EXERCISES.length*100)+"%";$("#medication-name").textContent=exercise.name;$("#medication-instruction").textContent=exercise.instruction;$("#medication-distribution").replaceChildren(...distribution(records,STATUS_OPTIONS));$("#medication-correction").hidden=!revealed;$("#medication-correct-answer").textContent="Statut attendu : "+STATUS_OPTIONS.find(option=>option.id===exercise.expected).label;$("#medication-explanation").textContent=exercise.feedback;$("#medication-route").textContent=exercise.route;$("#medication-status").textContent=exercise.officialStatus;$("#reveal-medication").hidden=revealed;$("#next-medication").hidden=!revealed;$("#next-medication").textContent=index===MEDICATION_EXERCISES.length-1?"Afficher le bilan":"Recherche suivante"}
function render(value){session=value;const participants=people();$("#participants").textContent=participants.length;$("#status").textContent=label(value);$("#connection").textContent="Mise à jour en direct";$("#waiting").hidden=value.status!=="waiting";$("#activity").hidden=value.status!=="activity"||!!value.phase&&value.phase!=="quiz";$("#stage-two-panel").hidden=value.status!=="activity"||value.phase!=="medicationIntro";$("#medication-panel").hidden=value.status!=="activity"||value.phase!=="medications";$("#final-panel").hidden=value.status!=="final";$("#closed").hidden=value.status!=="closed";$("#start").disabled=!participants.length;if(value.status==="activity"&&value.phase==="medications")renderMedication();else if(value.status==="activity"&&(value.phase==="quiz"||!value.phase))renderQuiz();else $("#answered").textContent="0"}
async function change(values){if(busy)return;busy=true;try{await update(ref(database,"sessions/"+code),values)}finally{busy=false}}
$("#start").onclick=()=>change({status:"activity",phase:"quiz",currentQuestion:0,feedbackRevealed:false,quizStartedAt:serverTimestamp()});
$("#reveal").onclick=()=>change({feedbackRevealed:true});
$("#next").onclick=()=>{const index=Math.min(Number(session.currentQuestion)||0,QUESTIONS.length-1);return index===QUESTIONS.length-1?change({phase:"medicationIntro",feedbackRevealed:false,quizFinishedAt:serverTimestamp()}):change({currentQuestion:index+1,feedbackRevealed:false})};
$("#launch-medications").onclick=()=>change({phase:"medications",currentMedication:0,medicationFeedbackRevealed:false,medicationStageStartedAt:serverTimestamp()});
$("#reveal-medication").onclick=()=>change({medicationFeedbackRevealed:true});
$("#next-medication").onclick=()=>{const index=Math.min(Number(session.currentMedication)||0,MEDICATION_EXERCISES.length-1);return index===MEDICATION_EXERCISES.length-1?change({status:"final",phase:"complete",activityFinishedAt:serverTimestamp()}):change({currentMedication:index+1,medicationFeedbackRevealed:false})};
$("#close").onclick=()=>change({status:"closed",closedAt:serverTimestamp()});
$("#login-form").onsubmit=async event=>{event.preventDefault();try{await signInWithEmailAndPassword(auth,EMAIL,$("#secret").value.trim())}catch(error){$("#login-message").textContent="Code incorrect."}};
async function open(user){if(code.length!==6)throw Error("Code incorrect");const sessionRef=ref(database,"sessions/"+code),snapshot=await get(sessionRef);if(!snapshot.exists()||snapshot.val().activity!=="labo-interdictions"||snapshot.val().facilitatorId!==user.uid)throw Error("Session inaccessible");top(null);render(snapshot.val());stopSession=onValue(sessionRef,snapshot=>snapshot.exists()&&render(snapshot.val()))}
onAuthStateChanged(auth,user=>{if(!user||user.isAnonymous){top($("#login-panel"));return}open(user).catch(error=>{$("#error-message").textContent=error.message;top($("#error-panel"))})});
addEventListener("pagehide",()=>stopSession?.());
