import * as pdfjsLib from "https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.624/build/pdf.min.mjs";

pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.624/build/pdf.worker.min.mjs";
const PDF_URL="../documents/Livret Santé Performance.pdf",$=selector=>document.querySelector(selector);
let pdf=null,totalPages=0,currentPage=1,zoom=1,renderToken=0,touchStartX=0;
const isSinglePage=()=>matchMedia("(max-width: 760px)").matches;
function spreadStart(page){return isSinglePage()?page:page-((page-1)%2)}
async function renderCanvas(container,pageNumber,token){if(pageNumber<1||pageNumber>totalPages){container.hidden=true;return}container.hidden=false;const sourcePage=Math.ceil(pageNumber/2),half=(pageNumber-1)%2,page=await pdf.getPage(sourcePage);if(token!==renderToken)return;const base=page.getViewport({scale:1}),availableWidth=isSinglePage()?Math.min(innerWidth-44,720):Math.min((innerWidth-100)/2,620),scale=Math.max(.25,availableWidth/(base.width/2))*zoom,viewport=page.getViewport({scale}),ratio=devicePixelRatio||1,offscreen=document.createElement("canvas"),canvas=container.querySelector("canvas"),pageWidth=viewport.width/2;offscreen.width=Math.floor(viewport.width*ratio);offscreen.height=Math.floor(viewport.height*ratio);await page.render({canvasContext:offscreen.getContext("2d"),viewport,transform:ratio===1?null:[ratio,0,0,ratio,0,0]}).promise;if(token!==renderToken)return;canvas.width=Math.floor(pageWidth*ratio);canvas.height=Math.floor(viewport.height*ratio);canvas.style.width=`${pageWidth}px`;canvas.style.height=`${viewport.height}px`;canvas.getContext("2d").drawImage(offscreen,Math.floor(half*pageWidth*ratio),0,Math.floor(pageWidth*ratio),offscreen.height,0,0,canvas.width,canvas.height)}
async function renderBook(direction="next"){if(!pdf)return;currentPage=Math.max(1,Math.min(currentPage,totalPages));currentPage=spreadStart(currentPage);const token=++renderToken,book=$("#book");book.classList.remove("turn-next","turn-previous");void book.offsetWidth;book.classList.add(direction==="previous"?"turn-previous":"turn-next");try{await Promise.all([renderCanvas($("#page-left"),currentPage,token),renderCanvas($("#page-right"),isSinglePage()?0:currentPage+1,token)]);if(token!==renderToken)return;$("#loading").hidden=true;const end=!isSinglePage()&&currentPage<totalPages?currentPage+1:currentPage;$("#page-status").textContent=end===currentPage?`Page ${currentPage}`:`Pages ${currentPage}–${end}`;$("#page-input").value=currentPage;$("#previous").disabled=currentPage===1;$("#next").disabled=end>=totalPages}catch(error){showError(error)}}
function animatePageTurn(direction){if(matchMedia("(prefers-reduced-motion: reduce)").matches)return;document.querySelector(".turning-sheet")?.remove();const book=$("#book"),source=direction==="next"&&!isSinglePage()?$("#page-right"):$("#page-left"),sourceCanvas=source.querySelector("canvas"),sourceBox=source.getBoundingClientRect(),bookBox=book.getBoundingClientRect();if(source.hidden||!sourceCanvas.width)return;const sheet=document.createElement("div"),front=document.createElement("div"),back=document.createElement("div"),copy=document.createElement("canvas");sheet.className=`turning-sheet ${direction}`;front.className="sheet-face sheet-front";back.className="sheet-face sheet-back";sheet.style.left=`${sourceBox.left-bookBox.left+book.scrollLeft}px`;sheet.style.top=`${sourceBox.top-bookBox.top+book.scrollTop}px`;sheet.style.width=`${sourceBox.width}px`;sheet.style.height=`${sourceBox.height}px`;copy.width=sourceCanvas.width;copy.height=sourceCanvas.height;copy.getContext("2d").drawImage(sourceCanvas,0,0);front.append(copy);sheet.append(front,back);book.append(sheet);sheet.addEventListener("animationend",()=>sheet.remove(),{once:true});setTimeout(()=>sheet.remove(),1100)}
function move(delta){const step=isSinglePage()?1:2,current=currentPage+delta*step;if(current<1||current>totalPages)return;const direction=delta<0?"previous":"next";animatePageTurn(direction);requestAnimationFrame(()=>{currentPage=current;renderBook(direction)})}
function showError(error){console.error(error);$("#loading").hidden=true;$("#error").hidden=false;$("#error").textContent="Le livret n’a pas pu être affiché. Utilisez le bouton d’ouverture en plein écran."}
$("#previous").onclick=()=>move(-1);$("#next").onclick=()=>move(1);$("#zoom-in").onclick=()=>{zoom=Math.min(1.5,zoom+.1);renderBook()};$("#zoom-out").onclick=()=>{zoom=Math.max(.6,zoom-.1);renderBook()};$("#fullscreen").onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();$("#page-input").onchange=event=>{currentPage=Number(event.target.value)||1;renderBook()};addEventListener("keydown",event=>{if(event.key==="ArrowLeft")move(-1);if(event.key==="ArrowRight")move(1)});$("#book").addEventListener("touchstart",event=>touchStartX=event.changedTouches[0].clientX,{passive:true});$("#book").addEventListener("touchend",event=>{const distance=event.changedTouches[0].clientX-touchStartX;if(Math.abs(distance)>55)move(distance>0?-1:1)},{passive:true});let resizeTimer;addEventListener("resize",()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>renderBook(),180)});
try{pdf=await pdfjsLib.getDocument(PDF_URL).promise;totalPages=pdf.numPages*2;$("#page-total").textContent=`sur ${totalPages}`;$("#page-input").max=totalPages;await renderBook()}catch(error){showError(error)}
