import { CONSEQUENCES, CATEGORIES, FALSE_IDEAS, FINAL_MESSAGE, shuffle } from "../../onde-choc/content.js";

const $=s=>document.querySelector(s);let selectedCard=null;
const targets=[...CATEGORIES,{id:"false",title:"Ce n’est pas une conséquence du dopage"}];
function card(item){const button=document.createElement("button");button.type="button";button.className="drag-card";button.draggable=true;button.dataset.id=item.id;button.textContent=item.text;button.onclick=()=>selectCard(button);button.ondragstart=e=>{e.dataTransfer.setData("text/plain",item.id);button.classList.add("dragging")};button.ondragend=()=>button.classList.remove("dragging");return button}
function selectCard(button){document.querySelectorAll(".drag-card.selected").forEach(x=>x.classList.remove("selected"));selectedCard=selectedCard===button?null:button;if(selectedCard)selectedCard.classList.add("selected")}
function move(id,target){const node=document.querySelector(`.drag-card[data-id="${id}"]`);if(!node)return;target.querySelector(".zone-content").append(node);node.dataset.placed=target.dataset.category;selectedCard=null;node.classList.remove("selected");updateCounts()}
function updateCounts(){document.querySelectorAll(".drop-zone").forEach(z=>z.querySelector(".zone-count").textContent=`${z.querySelectorAll(".drag-card").length} carte(s)`)}
function render(){selectedCard=null;const bank=$("#cards");bank.replaceChildren(...shuffle(CONSEQUENCES).map(card));$("#drop-zones").innerHTML=targets.map(t=>`<section class="drop-zone" data-category="${t.id}" tabindex="0"><header><strong>${t.title}</strong><span class="zone-count">0 carte</span></header><div class="zone-content"></div></section>`).join("");document.querySelectorAll(".drop-zone").forEach(zone=>{zone.ondragover=e=>{e.preventDefault();zone.classList.add("target")};zone.ondragleave=()=>zone.classList.remove("target");zone.ondrop=e=>{e.preventDefault();zone.classList.remove("target");move(e.dataTransfer.getData("text/plain"),zone)};zone.onclick=e=>{if(selectedCard&&!e.target.closest(".drag-card"))move(selectedCard.dataset.id,zone)};zone.onkeydown=e=>{if((e.key==="Enter"||e.key===" ")&&selectedCard){e.preventDefault();move(selectedCard.dataset.id,zone)}}});$("#form-message").textContent="";$("#question").hidden=false;$("#correction").hidden=true;$("#question").scrollIntoView({block:"start"})}
$("#quiz-form").onsubmit=e=>{e.preventDefault();const unplaced=$("#cards").querySelectorAll(".drag-card").length;if(unplaced){$("#form-message").textContent=`Il reste ${unplaced} carte${unplaced>1?"s":""} à classer.`;return}const placements=new Map([...document.querySelectorAll(".drag-card")].map(x=>[x.dataset.id,x.dataset.placed]));const mistakes=CONSEQUENCES.filter(x=>placements.get(x.id)!==(x.category||"false"));const correct=CONSEQUENCES.length-mistakes.length;const result=`${correct} / ${CONSEQUENCES.length} réponses justes`;const categoryName=id=>targets.find(x=>x.id===id)?.title||"";$("#answer-feedback").className=`answer-feedback ${mistakes.length?"needs-review":"all-correct"}`;$("#answer-feedback").innerHTML=mistakes.length?`<strong>${result}</strong><p>Certaines cartes sont à revoir. Voici où les replacer :</p><ul>${mistakes.map(x=>`<li><span>${x.text}</span><strong>→ ${categoryName(x.category||"false")}</strong></li>`).join("")}</ul>`:`<strong>${result}</strong><p>Ton classement est juste : tu as correctement distingué les trois familles de conséquences et les idées fausses.</p>`;$("#category-results").innerHTML=CATEGORIES.map(category=>`<article data-category="${category.id}"><h3>${category.title}</h3><ul>${CONSEQUENCES.filter(x=>x.category===category.id).map(x=>`<li>${x.short}</li>`).join("")}</ul></article>`).join("");$("#false-ideas-text").textContent=FALSE_IDEAS;$("#final-message").textContent=FINAL_MESSAGE;$("#question").hidden=true;$("#correction").hidden=false;$("#correction").scrollIntoView({block:"start"})};
$("#restart").onclick=render;render();
