import { initializeApp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import { getAuth,onAuthStateChanged,signInWithEmailAndPassword } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { getDatabase,ref,get,onValue,update,serverTimestamp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-database.js";
import { MOMENTS,FINAL_MESSAGE } from "../situations.js";
const updateReviewImage=()=>{const title=document.querySelector("#review-title")?.textContent,item=MOMENTS.find(moment=>moment.title===title),image=document.querySelector("#review-image");if(item&&image){image.src=item.image;image.alt=`Illustration : ${item.title}`}};
addEventListener("DOMContentLoaded",()=>new MutationObserver(updateReviewImage).observe(document.querySelector("#review-title"),{childList:true}));
const config={apiKey:"AIzaSyCX6Y_ImG1YNEMY19pSSl4FxaHKqo72B3s",authDomain:"activites-procyclean.firebaseapp.com",databaseURL:"https://activites-procyclean-default-rtdb.europe-west1.firebasedatabase.app/",projectId:"activites-procyclean",storageBucket:"activites-procyclean.firebasestorage.app",messagingSenderId:"900663423725",appId:"1:900663423725:web:bc51501dcf653bfd1052e4"};
const auth=getAuth(initializeApp(config)),database=getDatabase(),$=s=>document.querySelector(s),EMAIL="prevention.dopage@ffc.fr";let session,busy=false,stopSession=null,code=String(new URLSearchParams(location.search).get("session")||"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6);$("#session-code").textContent=$("#waiting-code").textContent=code||"—";
function top(panel){["#loading-panel","#login-panel","#error-panel"].forEach(id=>$(id).hidden=$(id)!==panel);$("#content").hidden=panel!==null}function people(){return Object.values(session?.participants||{})}function label(status){return({waiting:"En attente",activity:"Parcours",review:"Mise en commun",final:"Bilan",closed:"Terminée"})[status]||status}
function cards(item){const participants=people(),counts=item.choices.map(()=>0);participants.forEach(p=>{const choice=p.answers?.[item.id]?.choice;if(Number.isInteger(choice)&&counts[choice]!==undefined)counts[choice]+=1});const total=counts.reduce((a,b)=>a+b,0);$("#results").replaceChildren(...item.choices.map((text,index)=>{const article=document.createElement("article"),percent=total?Math.round(counts[index]/total*100):0;article.innerHTML=`<span>${text}</span><strong>${counts[index]} · ${percent} %</strong><div><i style="width:${percent}%"></i></div>`;return article}))}
function renderReview(){const index=Math.min(Number(session.reviewIndex)||0,MOMENTS.length-1),item=MOMENTS[index],revealed=Boolean(session.reviewRevealed);$("#review-progress").textContent=`Moment ${index+1} sur ${MOMENTS.length} · ${item.phase}`;$("#review-title").textContent=item.title;$("#review-scene").textContent=item.scene;$("#review-question").textContent=item.question;cards(item);$("#correction").hidden=!revealed;$("#correct-answer").textContent=`Réponse attendue : ${item.choices[item.correct]}`;$("#feedback").textContent=item.feedback;$("#reflex").textContent=`${item.type.toUpperCase()} DÉCOUVERT${item.type==="Droit"?"":"E"} — ${item.reflex}`;$("#reveal").hidden=revealed;$("#next").hidden=!revealed;$("#next").textContent=index===MOMENTS.length-1?"Afficher la fiche finale":"Moment suivant"}
function render(value){session=value;const participants=people(),completed=participants.filter(p=>p.status==="completed").length;$("#participant-count").textContent=participants.length;$("#completed-count").textContent=completed;$("#status").textContent=label(value.status);$("#connection-state").textContent="Mise à jour en direct";["waiting","activity","review","final","closed"].forEach(status=>$(status==="activity"?"#monitor-panel":`#${status}-panel`).hidden=value.status!==status);$("#start").disabled=!participants.length||busy;$("#progress-message").textContent=`${completed} parcours terminé${completed>1?"s":""} sur ${participants.length}.`;$("#progress").max=Math.max(participants.length,1);$("#progress").value=completed;const byMoment=MOMENTS.map((_,i)=>participants.filter(p=>(p.currentMoment||0)>i).length);$("#moment-progress").textContent=byMoment.map((count,i)=>`${i+1}: ${count}`).join(" · ");$("#final-message").textContent=FINAL_MESSAGE;if(value.status==="review")renderReview()}
async function change(values){if(busy)return;busy=true;try{await update(ref(database,`sessions/${code}`),values)}catch(error){console.error(error);$("#action-message").textContent="L’action n’a pas pu être enregistrée."}finally{busy=false}}
$("#start").onclick=()=>change({status:"activity",activityStartedAt:serverTimestamp()});$("#review").onclick=()=>change({status:"review",reviewIndex:0,reviewRevealed:false,reviewStartedAt:serverTimestamp()});$("#reveal").onclick=()=>change({reviewRevealed:true});$("#next").onclick=()=>{const index=Number(session.reviewIndex)||0;return index===MOMENTS.length-1?change({status:"final",finalStartedAt:serverTimestamp()}):change({reviewIndex:index+1,reviewRevealed:false})};$("#close").onclick=()=>change({status:"closed",closedAt:serverTimestamp()});$("#login-form").addEventListener("submit",async event=>{event.preventDefault();try{await signInWithEmailAndPassword(auth,EMAIL,$("#secret").value.trim())}catch(error){console.error(error);$("#login-message").textContent="Le code confidentiel est incorrect."}});
async function open(user){if(code.length!==6){$("#error-message").textContent="Code de session incorrect.";top($("#error-panel"));return}const sessionRef=ref(database,`sessions/${code}`),snap=await get(sessionRef);if(!snap.exists()||snap.val().activity!=="droits-controle"||snap.val().facilitatorId!==user.uid){$("#error-message").textContent="Cette session n’est pas accessible.";top($("#error-panel"));return}top(null);render(snap.val());stopSession=onValue(sessionRef,value=>value.exists()&&render(value.val()))}onAuthStateChanged(auth,user=>{if(!user||user.isAnonymous){top($("#login-panel"));return}open(user).catch(error=>{console.error(error);$("#error-message").textContent="Chargement impossible.";top($("#error-panel"))})});addEventListener("pagehide",()=>stopSession?.());
