import{VRADS,byId,shuffled}from"../../vrad-sanctions/vrad-data.js";
const $=s=>document.querySelector(s),screens=["intro","discover","transition","classification","sanctions","final"].map(id=>$("#"+id)),storageKey="procyclean-vrad-sanctions-v3";
const CLASSIFICATION={presence:"athlete",use:"athlete",evasion:"athlete",whereabouts:"athlete",tampering:"both",possession:"both",trafficking:"both",administration:"both",complicity:"both",association:"both",retaliation:"both"};
let state={discovery:0,discovered:[],classification:{},classificationDone:false,links:{},linksDone:false},selected=null,validated=false,cachedOptions=[],drag=null;
try{const saved=JSON.parse((window.procycleanActivityStorage || localStorage).getItem(storageKey));if(saved?.discovered)state={...state,...saved}}catch{}
const save=()=>(window.procycleanActivityStorage || localStorage).setItem(storageKey,JSON.stringify(state));
function show(screen){screens.forEach(item=>item.hidden=item!==screen);requestAnimationFrame(()=>screen.scrollIntoView({behavior:"smooth",block:"center"}))}
function codeBook(){$("#code-grid").replaceChildren(...VRADS.map((item,index)=>{const card=document.createElement("article"),open=state.discovered.includes(item.id);card.className="code-entry"+(open?"":" locked");card.innerHTML=`<small>${open?item.article:"Règle "+(index+1)}</small><strong>${open?item.short:"À découvrir"}</strong>`;return card}))}
function renderDiscovery(){const item=VRADS[state.discovery];selected=null;validated=false;cachedOptions=shuffled([item,...shuffled(VRADS.filter(v=>v.id!==item.id)).slice(0,3)]);$("#discover-count").textContent=`SITUATION ${state.discovery+1} / ${VRADS.length}`;$("#discover-progress").style.width=`${(state.discovery+1)/VRADS.length*100}%`;$("#scenario").textContent=item.scenario;$("#discover-feedback").hidden=true;$("#validate-discovery").hidden=false;$("#validate-discovery").disabled=true;$("#next-discovery").hidden=true;$("#discover-choices").replaceChildren(...cachedOptions.map(option=>{const b=document.createElement("button");b.className="answer-card";b.textContent=option.short;b.onclick=()=>{selected=option.id;document.querySelectorAll("#discover-choices .answer-card").forEach(x=>x.classList.toggle("selected",x===b));$("#validate-discovery").disabled=false};return b}));codeBook();show($("#discover"))}
$("#validate-discovery").onclick=()=>{if(!selected||validated)return;validated=true;const item=VRADS[state.discovery],ok=selected===item.id;window.ProcycleanGroup?.record("1-identification-"+state.discovery,item.scenario,byId(selected)?.short||selected,item.short,item.official,ok);state.discovered=[...new Set([...state.discovered,item.id])];save();document.querySelectorAll("#discover-choices .answer-card").forEach((b,i)=>{b.disabled=true;b.classList.toggle("correct",cachedOptions[i].id===item.id);b.classList.toggle("wrong",cachedOptions[i].id===selected&&!ok)});$("#discover-feedback").className="feedback "+(ok?"good":"bad");$("#discover-feedback-title").textContent=ok?"✓ Bonne identification":"✕ Ce n’était pas cette règle";$("#discover-feedback-text").textContent=`La bonne réponse est « ${item.short} » (${item.article}). ${item.official}.`;$("#discover-feedback").hidden=false;$("#validate-discovery").hidden=true;$("#next-discovery").hidden=false;$("#next-discovery").textContent=state.discovery===VRADS.length-1?"Voir mon Code complet":"Situation suivante";codeBook()};
$("#next-discovery").onclick=()=>{if(state.discovery<VRADS.length-1){state.discovery++;save();renderDiscovery()}else show($("#transition"))};

function createSortCard(item){const b=document.createElement("button");b.className="sort-card";b.dataset.dragId=item.id;b.textContent=item.short;b.onclick=()=>{if(state.classificationDone||drag?.moved)return;selected=selected===item.id?null:item.id;renderClassification()};return b}
function renderClassification(){const bank=$("#card-bank");bank.replaceChildren(...VRADS.filter(item=>!state.classification[item.id]).map(createSortCard));["athlete","entourage","both"].forEach(zone=>{$("#zone-"+zone).replaceChildren(...VRADS.filter(item=>state.classification[item.id]===zone).map(createSortCard))});document.querySelectorAll(`.sort-card[data-drag-id="${selected}"]`).forEach(item=>item.classList.add("selected"));const placed=Object.keys(state.classification).length;$("#classification-progress").textContent=`${placed} / ${VRADS.length} cartes placées`;$("#validate-classification").disabled=placed!==VRADS.length;$("#validate-classification").hidden=state.classificationDone;$("#begin-sanctions").hidden=!state.classificationDone;show($("#classification"))}
function placeCard(id,zone){if(!id||state.classificationDone)return;if(zone==="bank")delete state.classification[id];else state.classification[id]=zone;selected=null;save();renderClassification()}
document.querySelectorAll(".classification-zone").forEach(zone=>zone.onclick=event=>{if(event.target.closest(".sort-card"))return;placeCard(selected,zone.dataset.zone)});$("#card-bank").onclick=event=>{if(!event.target.closest(".sort-card"))placeCard(selected,"bank")};
function clearTargets(){document.querySelectorAll(".drop-target").forEach(x=>x.classList.remove("drop-target"))}function movePreview(x,y){if(drag)drag.preview.style.transform=`translate3d(${x-drag.offsetX}px,${y-drag.offsetY}px,0)`}
$("#classification").addEventListener("pointerdown",event=>{const source=event.target.closest("[data-drag-id]");if(!source||state.classificationDone||event.button>0)return;const box=source.getBoundingClientRect(),preview=document.createElement("div");preview.className="drag-preview";preview.textContent=source.textContent;preview.style.width=`${Math.min(box.width,260)}px`;document.body.append(preview);drag={pointerId:event.pointerId,id:source.dataset.dragId,source,preview,offsetX:Math.min(event.clientX-box.left,100),offsetY:Math.min(event.clientY-box.top,30),moved:false};source.classList.add("drag-source");source.setPointerCapture(event.pointerId);movePreview(event.clientX,event.clientY);event.preventDefault()});
$("#classification").addEventListener("pointermove",event=>{if(!drag||event.pointerId!==drag.pointerId)return;drag.moved=true;movePreview(event.clientX,event.clientY);clearTargets();document.elementFromPoint(event.clientX,event.clientY)?.closest(".classification-zone,.card-bank")?.classList.add("drop-target");event.preventDefault()});
function finishDrag(event){if(!drag||event.pointerId!==drag.pointerId)return;const current=drag,target=document.elementFromPoint(event.clientX,event.clientY)?.closest(".classification-zone,.card-bank");current.source.classList.remove("drag-source");current.preview.remove();clearTargets();drag=null;if(target)placeCard(current.id,target.dataset.zone||"bank")}
$("#classification").addEventListener("pointerup",finishDrag);$("#classification").addEventListener("pointercancel",finishDrag);
$("#validate-classification").onclick=()=>{const mistakes=VRADS.filter(item=>state.classification[item.id]!==CLASSIFICATION[item.id]);state.classificationDone=true;VRADS.forEach((item,i)=>window.ProcycleanGroup?.record("2-classement-"+i,"Qui peut commettre : "+item.short,({athlete:"Sportif",entourage:"Entourage",both:"Les deux"})[state.classification[item.id]],CLASSIFICATION[item.id]==="athlete"?"Sportif":"Les deux","",state.classification[item.id]===CLASSIFICATION[item.id]));save();const feedback=$("#classification-feedback");feedback.className="feedback classification-detail "+(mistakes.length?"bad":"good");feedback.innerHTML=mistakes.length?`<h3>${VRADS.length-mistakes.length}/${VRADS.length} cartes bien placées</h3><p>Voici les cartes à corriger :</p><ul>${mistakes.map(item=>`<li><strong>${item.short}</strong> devait être placée dans « ${CLASSIFICATION[item.id]==="athlete"?"Sportif":"Les deux"} ».</li>`).join("")}</ul><p><strong>Conclusion :</strong> la zone « Entourage du sportif » reste vide. Aucune VRAD ne peut être commise uniquement par l’entourage.</p>`:`<h3>✓ Les 11 cartes sont bien classées</h3><p><strong>La zone « Entourage du sportif » reste vide.</strong> Les quatre premières VRAD sont propres au sportif. Les sept autres peuvent être commises par le sportif ou par une autre personne de son entourage.</p><p>Ce classement ne désigne pas la personne présente dans le scénario : il indique qui peut juridiquement commettre la violation.</p>`;feedback.hidden=false;$("#validate-classification").hidden=true;$("#begin-sanctions").hidden=false;renderClassification()};

const SANCTIONS=[...new Set(VRADS.map(item=>item.sanction))];
function createConnectItem(label,id,type){const b=document.createElement("button");b.className="connect-item";b.dataset[type]=id;b.innerHTML=`<span>${label}</span><i class="connector-dot"></i>`;return b}
function renderConnections(){selected=null;$("#vrad-column").replaceChildren(...VRADS.map(item=>{const b=createConnectItem(item.short,item.id,"vrad");b.classList.toggle("linked",!!state.links[item.id]);b.onclick=()=>{if(state.linksDone)return;selected=selected===item.id?null:item.id;renderConnectionStates()};return b}));$("#sanction-column").replaceChildren(...SANCTIONS.map((label,index)=>{const b=createConnectItem(label,String(index),"sanction");b.onclick=()=>{if(!selected||state.linksDone)return;state.links[selected]=label;selected=null;save();renderConnections()};return b}));renderConnectionStates();show($("#sanctions"));requestAnimationFrame(drawLines)}
function renderConnectionStates(){document.querySelectorAll("[data-vrad]").forEach(b=>b.classList.toggle("selected",b.dataset.vrad===selected));const count=Object.keys(state.links).length;$("#connection-progress").textContent=`${count} liaison${count>1?"s":""} sur ${VRADS.length} réalisée${count>1?"s":""}`;$("#validate-sanctions").disabled=count!==VRADS.length}
function drawLines(){const board=$("#connection-board"),svg=$("#connection-lines"),box=board.getBoundingClientRect();svg.replaceChildren();if(innerWidth<=760)return;Object.entries(state.links).forEach(([id,label])=>{const left=document.querySelector(`[data-vrad="${id}"] .connector-dot`),index=SANCTIONS.indexOf(label),right=document.querySelector(`[data-sanction="${index}"] .connector-dot`);if(!left||!right)return;const a=left.getBoundingClientRect(),b=right.getBoundingClientRect(),x1=a.left+a.width/2-box.left,y1=a.top+a.height/2-box.top,x2=b.left+b.width/2-box.left,y2=b.top+b.height/2-box.top,path=document.createElementNS("http://www.w3.org/2000/svg","path"),curve=Math.max(35,(x2-x1)/2);path.setAttribute("d",`M ${x1} ${y1} C ${x1+curve} ${y1}, ${x2-curve} ${y2}, ${x2} ${y2}`);svg.append(path)})}
$("#validate-sanctions").onclick=()=>{const mistakes=VRADS.filter(item=>state.links[item.id]!==item.sanction);state.linksDone=true;VRADS.forEach((item,i)=>window.ProcycleanGroup?.record("3-sanction-"+i,item.short+" : quel principe de sanction ?",state.links[item.id],item.sanction,"La sanction réelle dépend des faits et des circonstances.",state.links[item.id]===item.sanction));save();VRADS.forEach(item=>{const b=document.querySelector(`[data-vrad="${item.id}"]`);b.classList.add(state.links[item.id]===item.sanction?"correct":"wrong")});const feedback=$("#sanction-feedback");feedback.className="feedback classification-detail "+(mistakes.length?"bad":"good");feedback.innerHTML=mistakes.length?`<h3>${VRADS.length-mistakes.length}/${VRADS.length} liaisons justes</h3><p>Les liaisons à retenir :</p><ul>${mistakes.map(item=>`<li><strong>${item.short}</strong> → ${item.sanction}</li>`).join("")}</ul><p>Ces durées sont des principes généraux : la sanction réelle dépend notamment de l’intention, de la faute et des circonstances.</p>`:`<h3>✓ Les 11 liaisons sont justes</h3><p>Tu as relié chaque VRAD à son principe de sanction. Plusieurs violations peuvent conduire au même type de sanction.</p><p>Attention : ces durées ne sont pas automatiques. Elles peuvent être adaptées selon les faits et les circonstances.</p>`;feedback.hidden=false;$("#validate-sanctions").hidden=true;$("#finish").hidden=false};
function renderFinal(){$("#final-list").replaceChildren(...VRADS.map(item=>{const a=document.createElement("article");a.innerHTML=`<strong>${item.short}</strong><br><span>${CLASSIFICATION[item.id]==="athlete"?"Sportif uniquement":"Sportif et entourage"} · ${item.sanction}</span>`;return a}));show($("#final"))}
$("#start").onclick=()=>state.discovered.length===VRADS.length?show($("#transition")):renderDiscovery();$("#begin-classification").onclick=renderClassification;$("#begin-sanctions").onclick=renderConnections;$("#finish").onclick=renderFinal;$("#restart").onclick=()=>{state={discovery:0,discovered:[],classification:{},classificationDone:false,links:{},linksDone:false};selected=null;(window.procycleanActivityStorage || localStorage).removeItem(storageKey);show($("#intro"))};addEventListener("resize",()=>requestAnimationFrame(drawLines));
document.addEventListener("click",event=>{const link=event.target.closest("a");if(!link)return;const path=new URL(link.href,location.href).pathname.replace(/\\/g,"/");if(path.endsWith("/activites/individuel/index.html")||path.endsWith("/activites/index.html"))(window.procycleanActivityStorage || localStorage).removeItem(storageKey)},true);


// Synchronisation de ce même parcours lorsqu’il est ouvert dans une séance.
window.ProcycleanGroup?.register({
 snapshot:()=>({state:{data:state,screen:screens.find(x=>!x.hidden)?.id},progress:state.linksDone?100:(state.discovered.length+Object.keys(state.classification).length+Object.keys(state.links).length)/(VRADS.length*3)*95,complete:state.linksDone}),
 restore:s=>{state=s.data;if(s.screen==="final"){renderFinal();return;}if(s.screen==="classification"){renderClassification();if(state.classificationDone)$("#validate-classification").click();return;}if(s.screen==="sanctions"){renderConnections();if(state.linksDone)$("#validate-sanctions").click();return;}if(s.screen==="discover"){state.discovery=Math.min(state.discovered.length,VRADS.length-1);renderDiscovery();return;}codeBook();show($("#"+(s.screen||"intro")));}
});
