import{CONVERSATIONS,CONTACTS,ACTIONS}from"../../briser-silence/content.js";
const $=s=>document.querySelector(s),screens=["intro","inbox","conversation","final"].map(x=>$("#"+x));let current=0,done=new Set(),unlocked=new Set();
function show(x){screens.forEach(s=>s.hidden=s!==x);x.scrollIntoView({block:"start"})}function contactCard(c){const locked=!unlocked.has(c.id);return `<span class="${locked?"locked":""}" title="${c.name}">${locked?"🔒":c.icon}<small>${c.name}</small></span>`}
function network(){$("#mini-contacts").innerHTML=CONTACTS.map(contactCard).join("")}function inbox(){network();$("#inbox-progress").textContent=`${done.size}/${CONVERSATIONS.length} conversations aidées`;$("#message-list").innerHTML=CONVERSATIONS.map((c,i)=>`<button class="message-preview ${done.has(i)?"done":""}" data-index="${i}" type="button"><span class="avatar">${c.avatar}</span><span><strong>${c.from}</strong><small>${c.preview}</small></span><b>${done.has(i)?"✓":"›"}</b></button>`).join("");document.querySelectorAll(".message-preview").forEach(b=>b.onclick=()=>open(+b.dataset.index));show($("#inbox"))}
function bubble(text,type="received"){const p=document.createElement("p");p.className=`bubble ${type}`;p.textContent=text;$("#chat").append(p)}function panel(title,text,body,button){$("#interaction").innerHTML=`<p class="interaction-step">${title}</p><p>${text}</p>${body}<p id="interaction-message"></p><button id="interaction-action" class="primary" type="button">${button}</button>`}
function open(i){current=i;const c=CONVERSATIONS[i];$("#contact-name").textContent=c.from;$("#chat").replaceChildren();const msg=document.createElement("p");msg.className="bubble received clue-message";c.parts.forEach((part,n)=>{const b=document.createElement("button");b.type="button";b.textContent=part.text;b.dataset.part=n;b.onclick=()=>b.classList.toggle("selected");msg.append(b)});$("#chat").append(msg);renderSignal();show($("#conversation"))}
function renderSignal(){panel("1 · REPÈRE LE SIGNAL D’ALERTE","Touche les mots ou expressions qui doivent t’alerter.","","Valider les indices");$("#interaction-action").onclick=()=>{const c=CONVERSATIONS[current],selected=[...document.querySelectorAll(".clue-message button.selected")].map(x=>+x.dataset.part),alerts=c.parts.map((x,i)=>x.alert?i:-1).filter(i=>i>=0),ok=alerts.every(i=>selected.includes(i))&&selected.every(i=>alerts.includes(i));document.querySelectorAll(".clue-message button").forEach((b,i)=>c.parts[i].alert&&b.classList.add("alert"));bubble(ok?"Tu as repéré les signaux importants.":c.signal,"system");renderActions()}}
function renderActions(){panel("2 · CHOISIS COMMENT AGIR","Toutes les situations ne conduisent pas nécessairement à un signalement.",`<div class="reply-list">${ACTIONS.map(x=>`<button data-action="${x.id}" type="button">${x.text}</button>`).join("")}</div>`,`Valider mon action`);document.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-action]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")});$("#interaction-action").onclick=validateAction}
function validateAction(){const selected=document.querySelector("[data-action].selected");if(!selected){$("#interaction-message").textContent="Choisis une action.";return}const c=CONVERSATIONS[current],id=selected.dataset.action,ok=c.actions.includes(id);bubble(ACTIONS.find(x=>x.id===id).text,"sent");if(id==="fairplay"&&c.actions.includes("fairplay")){bubble("Fair-Play peut recevoir ce fait observé de manière confidentielle.","system");renderFairPlay()}else{bubble(ok?c.followup:`Cette situation appelle plutôt : ${c.actions.map(id=>ACTIONS.find(x=>x.id===id).text).join(" ou ")} ${c.followup}`,"received");renderContacts()}}
function renderContacts(){const c=CONVERSATIONS[current],all=[...CONTACTS.filter(x=>x.id!=="fairplay"),{id:"social",icon:"📣",name:"Les réseaux sociaux"}];panel("3 · TROUVE LE BON INTERLOCUTEUR","Tu peux choisir plusieurs contacts adaptés.",`<div class="contact-list">${all.map(x=>`<label><input type="checkbox" value="${x.id}"><span>${x.icon}</span><strong>${x.name}</strong></label>`).join("")}</div>`,`Orienter la personne`);$("#interaction-action").onclick=validateContacts}
function validateContacts(){const c=CONVERSATIONS[current],selected=[...document.querySelectorAll(".contact-list input:checked")].map(x=>x.value);if(!selected.length){$("#interaction-message").textContent="Choisis au moins un interlocuteur.";return}const reliable=CONTACTS.filter(x=>c.contacts.includes(x.id)&&x.id!=="fairplay").map(x=>x.name).join(", ");$("#interaction").innerHTML=`<p class="source-feedback"><strong>✓ Sources fiables identifiées</strong><span>${reliable||"Fair-Play – plateforme de signalement de l’AFLD"}</span></p><button id="finish-conversation" class="primary" type="button">J’ai compris</button>`;$("#finish-conversation").onclick=completeConversation}
function renderFairPlay(){$("#interaction").innerHTML=`<div class="fairplay-intro"><strong>Fair-Play – AFLD</strong><p>Tu peux transmettre une suspicion, un renseignement ou un fait observé ou rapporté.</p><p>Précise seulement ce que tu sais réellement, sans inventer ni accuser publiquement.</p></div><button id="prepare-report" class="primary" type="button">Préparer mon signalement</button>`;$("#prepare-report").onclick=simulationOne}
function simulationOne(){panel("1 · ORIGINE DE L’INFORMATION","Comment as-tu obtenu cette information ?",`<div class="reply-list">${["Je l’ai vue.","Une personne me l’a racontée.","Je l’ai entendue, sans savoir si elle est vraie.","C’est seulement une supposition."].map((x,i)=>`<button data-sim="${i}">${x}</button>`).join("")}</div>`,`Continuer`);wireSingle(simulationTwo)}function wireSingle(next){document.querySelectorAll("[data-sim]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-sim]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")});$("#interaction-action").onclick=()=>document.querySelector("[data-sim].selected")?next():($("#interaction-message").textContent="Choisis une réponse.")}
function simulationTwo(){const useful=["Ce qui s’est passé","Le lieu","La date ou la période","Les personnes concernées, si elles sont connues","Le produit évoqué","Les messages, photos ou documents disponibles"],falseItems=["Inventer les informations manquantes","Exagérer la situation","Publier un nom sur les réseaux sociaux"];panel("2 · INFORMATIONS UTILES","Sélectionne les informations utiles.",`<div class="contact-list">${[...useful,...falseItems].map((x,i)=>`<label><input type="checkbox" data-useful="${i<useful.length}"><strong>${x}</strong></label>`).join("")}</div>`,`Continuer`);$("#interaction-action").onclick=()=>document.querySelector(".contact-list input:checked")?simulationThree():($("#interaction-message").textContent="Sélectionne au moins une information.")}
function simulationThree(){panel("3 · MODE DE TRANSMISSION","Comment veux-tu transmettre l’information ?",`<div class="reply-list">${["En indiquant mon identité.","En restant anonyme.","En demandant l’aide d’un adulte de confiance."].map((x,i)=>`<button data-sim="${i}">${x}</button>`).join("")}</div>`,`Préparer le signalement`);wireSingle(reportReady)}
function reportReady(){$("#interaction").innerHTML=`<div class="source-feedback"><strong>Ton signalement est prêt.</strong><span>Dans une situation réelle, ces informations peuvent être transmises confidentiellement à l’AFLD sur Fair-Play. Si tu es jeune ou hésites, demande l’aide d’un adulte de confiance.</span></div><div class="report-actions"><a class="secondary" href="https://www.afld.fr/la-lutte-antidopage/controles-et-investigations/signaler-un-fait-de-dopage/" target="_blank" rel="noopener">Découvrir la plateforme Fair-Play</a><button id="finish-report" class="primary">Terminer la simulation</button></div>`;$("#finish-report").onclick=completeConversation}
function completeConversation(){const c=CONVERSATIONS[current];unlocked.add(c.unlock);done.add(current);done.size===CONVERSATIONS.length?finish():inbox()}function finish(){unlocked.add("fairplay");$("#final-contacts").innerHTML=CONTACTS.map(contactCard).join("");show($("#final"))}
$("#start").onclick=inbox;$("#back-inbox").onclick=inbox;$("#restart").onclick=()=>{done.clear();unlocked.clear();show($("#intro"))};
