import { initializeApp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import { getAuth,onAuthStateChanged,signInAnonymously } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { getDatabase,ref,get,onValue,runTransaction,serverTimestamp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-database.js";
import { MOMENTS,PHASES,RIGHTS,RESPONSIBILITIES,FINAL_MESSAGE } from "../situations.js";
const config={apiKey:"AIzaSyCX6Y_ImG1YNEMY19pSSl4FxaHKqo72B3s",authDomain:"activites-procyclean.firebaseapp.com",databaseURL:"https://activites-procyclean-default-rtdb.europe-west1.firebasedatabase.app/",projectId:"activites-procyclean",storageBucket:"activites-procyclean.firebasestorage.app",messagingSenderId:"900663423725",appId:"1:900663423725:web:bc51501dcf653bfd1052e4"};
const auth=getAuth(initializeApp(config)),database=getDatabase(),$=s=>document.querySelector(s),screens=["loading","error","waiting","moment","feedback","completed","final"].map(id=>$("#"+id));
let user,session,code,busy=false,feedbackId=null,stopSession=null;
function show(screen){screens.forEach(item=>item.hidden=item!==screen);scrollTo({top:0,behavior:"smooth"})}
function fail(message){$("#error-message").textContent=message;show($("#error"))}
function authUser(){return new Promise((resolve,reject)=>{const stop=onAuthStateChanged(auth,async current=>{try{if(current?.isAnonymous){stop();resolve(current)}else{const result=await signInAnonymously(auth);stop();resolve(result.user)}}catch(error){stop();reject(error)}},reject)})}
function list(container,items){container.replaceChildren(...items.map(text=>{const li=document.createElement("li");li.textContent=text;return li}))}
function known(participant,type){return MOMENTS.filter(item=>item.type===type&&participant.answers?.[item.id]).map(item=>item.reflex)}
function timeline(current){$("#timeline").replaceChildren(...PHASES.map(phase=>{const span=document.createElement("span");span.textContent=phase;const phaseIndex=PHASES.indexOf(phase),currentIndex=PHASES.indexOf(current);if(phaseIndex<currentIndex)span.className="done";if(phaseIndex===currentIndex)span.className="current";return span}))}
function choices(item){$("#choices").replaceChildren(...item.choices.map((text,index)=>{const label=document.createElement("label"),input=document.createElement("input");input.type="radio";input.name="choice";input.value=index;label.append(input,document.createTextNode(text));return label}))}
function render(value){session=value;const participant=value.participants?.[user.uid];if(!participant)return;$("#participant-label").textContent=`Participant ${participant.participantNumber}`;
  if(value.status==="closed"||value.status==="final"){list($("#final-rights"),RIGHTS);list($("#final-responsibilities"),RESPONSIBILITIES);$("#final-message").textContent=FINAL_MESSAGE;show($("#final"));return}
  if(value.status==="waiting"){show($("#waiting"));return}const answers=participant.answers||{},index=MOMENTS.findIndex(item=>!answers[item.id]);
  if(index<0){show($("#completed"));return}if(value.status!=="activity"){show($("#completed"));return}const item=MOMENTS[index];
  if(feedbackId===item.id){return}feedbackId=null;timeline(item.phase);$("#progress-label").textContent=`Moment clé ${index+1} sur ${MOMENTS.length}`;$("#phase-label").textContent=item.phase;$("#moment-title").textContent=item.title;$("#scene-text").textContent=item.scene;$("#question").textContent=item.question;choices(item);list($("#rights-mini"),known(participant,"Droit"));list($("#responsibilities-mini"),known(participant,"Responsabilité"));$("#answer-message").textContent="";$("#submit").disabled=false;show($("#moment"))}
$("#answer-form").addEventListener("submit",async event=>{event.preventDefault();if(busy)return;const selected=new FormData(event.currentTarget).get("choice"),participant=session.participants[user.uid],item=MOMENTS.find(m=>!participant.answers?.[m.id]);if(selected===null){$("#answer-message").textContent="Choisis une réponse.";return}busy=true;$("#submit").disabled=true;const choice=Number(selected),correct=choice===item.correct;
  try{const result=await runTransaction(ref(database,`sessions/${code}/participants/${user.uid}`),current=>{if(!current||current.answers?.[item.id])return;const answers={...(current.answers||{}),[item.id]:{choice,correct,answeredAt:Date.now()}},complete=Object.keys(answers).length===MOMENTS.length;return {...current,answers,status:complete?"completed":"in-progress",currentMoment:Object.keys(answers).length,startedAt:current.startedAt||Date.now(),...(complete?{completedAt:Date.now()}:{})}});if(result.committed){feedbackId=item.id;$("#feedback-result").textContent=correct?"Bon raisonnement":"À retenir";$("#feedback-result").className=`result ${correct?"correct":"learn"}`;$("#feedback-title").textContent=item.title;$("#feedback-text").textContent=item.feedback;$("#discovery-type").textContent=`${item.type.toUpperCase()} DÉCOUVERT${item.type==="Droit"?"":"E"}`;$("#discovery-reflex").textContent=item.reflex;show($("#feedback"))}}catch(error){console.error(error);$("#answer-message").textContent="Enregistrement impossible. Réessaie."}finally{busy=false}});
$("#continue").onclick=()=>{feedbackId=null;render(session)};
async function register(){const result=await runTransaction(ref(database,`sessions/${code}`),value=>{if(!value||value.activity!=="droits-controle")return;value.participants||={};const old=value.participants[user.uid];if(old?.participantNumber)return value;const number=(value.nextParticipantNumber||0)+1;value.nextParticipantNumber=number;value.participants[user.uid]={...old,participantNumber:number,joinedAt:old?.joinedAt||serverTimestamp(),status:"waiting",answers:old?.answers||{}};return value});if(!result.committed)throw new Error("Inscription impossible")}
async function load(){code=String(new URLSearchParams(location.search).get("session")||"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6);if(code.length!==6){fail("Le code de session est absent ou incorrect.");return}try{user=await authUser();const sessionRef=ref(database,`sessions/${code}`),snap=await get(sessionRef);if(!snap.exists()||snap.val().activity!=="droits-controle"){fail("Cette session n’est pas disponible.");return}await register();stopSession=onValue(sessionRef,snapshot=>snapshot.exists()?render(snapshot.val()):fail("Cette session n’est plus disponible."),()=>fail("Synchronisation interrompue."))}catch(error){console.error(error);fail("La connexion à l’activité a échoué.")}}
const sceneImageObserver=new MutationObserver(()=>{const item=MOMENTS.find(moment=>moment.title===$("#moment-title").textContent);if(item){$("#scene-image").src=item.image;$("#scene-image").alt=`Illustration : ${item.title}`}});
sceneImageObserver.observe($("#moment-title"),{childList:true});
const feedbackObserver=new MutationObserver(()=>{const incorrect=$("#feedback-result").classList.contains("learn"),item=MOMENTS.find(moment=>moment.title===$("#feedback-title").textContent),label=incorrect?"Réponse incorrecte":"Bonne réponse";if($("#feedback-result").textContent!==label)$("#feedback-result").textContent=label;$("#expected-answer").hidden=!incorrect;$("#expected-answer").textContent=incorrect&&item?`La réponse attendue était : « ${item.choices[item.correct]} »`:""});
feedbackObserver.observe($("#feedback-result"),{childList:true});
const finalFeedbackObserver=new MutationObserver(()=>{const answers=Object.values(session?.participants?.[user?.uid]?.answers||{}),correct=answers.filter(answer=>answer.correct).length;$("#final-feedback").textContent=correct===MOMENTS.length?`Excellent : ${correct} bons raisonnements sur ${MOMENTS.length}. Tu as reconnu tous les bons réflexes.`:`Tu as reconnu ${correct} bons réflexes sur ${MOMENTS.length}. Ta fiche ci-dessous t’aide à consolider les situations à retenir.`});
finalFeedbackObserver.observe($("#final-message"),{childList:true});
addEventListener("pagehide",()=>{stopSession?.();sceneImageObserver.disconnect();feedbackObserver.disconnect();finalFeedbackObserver.disconnect()});load();
