export const CONTACTS=[{id:"close",icon:"🏠",name:"Un proche"},{id:"coach",icon:"🚲",name:"Un entraîneur de confiance"},{id:"health",icon:"🩺",name:"Un professionnel de santé"},{id:"educator",icon:"🛡️",name:"Un éducateur antidopage"},{id:"fairplay",icon:"⚖️",name:"Fair-Play – signalement AFLD"}];
export const ACTIONS=[{id:"advice",text:"Je demande conseil."},{id:"trust",text:"J’en parle à une personne de confiance."},{id:"fairplay",text:"Je signale les faits sur Fair-Play."},{id:"silent",text:"Je garde le silence."}];
export const CONVERSATIONS=[
{from:"Noa",avatar:"N",preview:"On m’a proposé un produit…",parts:[{text:"Salut… Un coéquipier m’a donné "},{text:"un produit inconnu",alert:true},{text:" et m’a demandé "},{text:"de ne pas en parler",alert:true},{text:". Tu ferais quoi ?"}],signal:"Le contenu du produit est inconnu et le secret demandé est un signal d’alerte.",actions:["advice","trust"],followup:"Merci. À qui puis-je en parler ?",contacts:["close","coach","health","educator"],unlock:"close"},
{from:"Sami",avatar:"S",preview:"Je risque de perdre ma place…",parts:[{text:"On m’a dit que "},{text:"je risquais de perdre ma place",alert:true},{text:" si je refusais. "},{text:"Tout le monde le prend",alert:true},{text:", paraît-il."}],signal:"La peur de perdre sa place et la pression du groupe doivent alerter.",actions:["advice","trust"],followup:"Qui peut m’aider sans me juger ?",contacts:["close","coach","health","educator"],unlock:"coach"},
{from:"Léa",avatar:"L",preview:"Un adulte m’a demandé le secret…",parts:[{text:"Un adulte m’a proposé une substance : "},{text:"fais-moi confiance",alert:true},{text:" et surtout "},{text:"ne le dis à personne",alert:true},{text:"."}],signal:"Un adulte demande de garder secrète une situation risquée.",actions:["trust"],followup:"À quel autre adulte puis-je demander de l’aide ?",contacts:["close","coach","health","educator"],unlock:"health"},
{from:"Camille",avatar:"C",preview:"Tout le monde parle d’un sportif…",parts:[{text:"Tout le monde dit qu’un sportif se dope. "},{text:"Je vais publier son nom",alert:true},{text:" même si "},{text:"l’information n’est pas vérifiée",alert:true},{text:"."}],signal:"Il s’agit d’une rumeur non vérifiée qui ne doit pas être diffusée.",actions:["advice","trust"],followup:"À qui parler sans accuser ?",contacts:["close","coach","educator"],unlock:"educator"},
{from:"Hugo",avatar:"H",preview:"J’ai vu quelque chose de préoccupant…",parts:[{text:"J’ai "},{text:"vu directement",alert:true},{text:" une personne donner une substance interdite à un sportif et dire : "},{text:"personne ne le saura",alert:true},{text:"."}],signal:"Un fait préoccupant a été directement observé et une demande de secret l’accompagne.",actions:["trust","fairplay"],followup:"Je peux en parler et transmettre ce que je sais réellement.",contacts:["educator","fairplay"],unlock:"fairplay"}
];
