const $=s=>document.querySelector(s),screens=["intro","mission","feedback","final"].map(x=>$("#"+x));let step=0,lastMissionData=null;
const obligations=[
 ["Adresse complète du lieu où le sportif dort","both"],["Lieux et horaires d’entraînement","both"],["Lieux et horaires de travail ou d’études","both"],["Programme des compétitions","both"],["Mise à jour en cas de changement","both"],["Transmission dans ADAMS ou Athlete Central","both"],["Informations assez précises pour trouver le sportif","both"],["Créneau quotidien de 60 minutes","target"],["Publier son emploi du temps sur les réseaux sociaux","none"],["Envoyer seulement son planning à son entraîneur","none"],["Prévenir uniquement par téléphone","none"],["Indiquer seulement le nom de la ville","none"],["Remplir uniquement lorsqu’un contrôle est annoncé","none"]
];
const coachInfo=[
 {id:"hotel",group:"Hébergement",text:"Hôtel des Quais, 12 quai Perrache à Lyon, chambre 308",useful:true},
 {id:"training",group:"Entraînement",text:"Entraînement mardi de 16 h 30 à 18 h 30 au vélodrome Georges-Préveral, 59 rue Pierre-Baratin",useful:true},
 {id:"slot",group:"Créneau",text:"Créneau de 60 minutes mardi de 20 h à 21 h, Hôtel des Quais, chambre 308",useful:true},
 {id:"competition",group:"Compétition",text:"Compétition mercredi à 10 h au Palais des Sports de Gerland, 350 avenue Jean-Jaurès",useful:true},
 {id:"night-two",group:"Hébergement",text:"Nuit de mercredi à l’Hôtel du Parc, 8 avenue des Frères-Lumière, chambre à confirmer",useful:true},
 {id:"breakfast",group:"Vie personnelle",text:"Petit-déjeuner prévu mercredi à 7 h 30",useful:false},
 {id:"menu",group:"Vie personnelle",text:"Le menu du dîner sera envoyé plus tard",useful:false},
 {id:"seat",group:"Transport",text:"Ta place dans le minibus est la numéro 6",useful:false},
 {id:"weather",group:"Information générale",text:"La météo annonce de la pluie mercredi",useful:false},
 {id:"coach-phone",group:"Contact",text:"Le coach reste joignable sur son téléphone personnel",useful:false}
];
const missions=[
 {title:"Identifier le statut",instruction:"Qui doit transmettre des informations de localisation ?",render:()=>`<div class="profiles"><label><input type="checkbox" name="athlete" value="alex"><strong>Alex · Aucun groupe</strong><span>Aucun courrier reçu.</span></label><label><input type="checkbox" name="athlete" value="sam"><strong>Sam · Groupe de contrôle</strong><span>Courrier de l’AFLD demandant ses localisations.</span></label><label><input type="checkbox" name="athlete" value="lea"><strong>Léa · Groupe cible</strong><span>Notification officielle d’inclusion.</span></label></div>`,valid:d=>{const x=d.getAll("athlete");return x.length===2&&x.includes("sam")&&x.includes("lea")},feedback:"Sam et Léa doivent transmettre leurs informations. Un sportif ne choisit pas lui-même son groupe : il en est informé officiellement."},
 {title:"Distribuer les obligations",instruction:"Pour chaque carte, choisis le groupe concerné.",render:()=>`<div class="obligation-list">${obligations.map((x,i)=>`<label><span>${x[0]}</span><select name="ob-${i}"><option value="">Choisir…</option><option value="target">Groupe cible</option><option value="control">Groupe de contrôle</option><option value="both">Les deux groupes</option><option value="none">Aucun des deux</option></select></label>`).join("")}</div>`,valid:d=>{lastMissionData=d;return obligations.every((x,i)=>Boolean(d.get(`ob-${i}`)))},get feedback(){const correct=obligations.filter((x,i)=>lastMissionData?.get(`ob-${i}`)===x[1]).length;return `${correct} / ${obligations.length} réponses justes. Groupe de contrôle : adresse complète de l’hébergement, lieux et horaires d’entraînement, travail ou études, compétitions, informations précises et mises à jour dans ADAMS ou Athlete Central. Groupe cible : toutes ces mêmes informations, avec en plus un créneau quotidien de 60 minutes. Les réseaux sociaux, un envoi au seul entraîneur, un simple appel, le seul nom de la ville ou l’attente d’un contrôle annoncé ne conviennent pas.`}},
 {title:"Compléter l’agenda de Léa",instruction:"Choisis les informations assez précises pour permettre de trouver Léa sans devoir l’appeler.",render:()=>`<div class="agenda"><header>AUJOURD’HUI · LÉA</header><label>Hébergement<select name="hotel"><option value="">Choisir…</option><option value="partial">Hôtel du Vélodrome</option><option value="precise">Hôtel du Vélodrome, 24 rue du Stade, chambre 214</option><option value="vague">Quelque part près du vélodrome</option></select></label><label>Entraînement<select name="training"><option value="">Choisir…</option><option value="precise">9 h à 12 h, Vélodrome, 8 avenue de la Piste</option><option value="partial">Dans la matinée au vélodrome</option><option value="vague">Entraînement habituel</option></select></label><label>Créneau de 60 minutes<select name="slot"><option value="">Choisir…</option><option value="vague">Dans la soirée</option><option value="precise">18 h à 19 h, Hôtel du Vélodrome, chambre 214</option><option value="partial">Après mon entraînement</option></select></label></div>`,valid:d=>{lastMissionData=d;return ["hotel","training","slot"].every(x=>Boolean(d.get(x)))},get feedback(){const fields=[["hotel","Hébergement : nom, adresse complète et chambre"],["training","Entraînement : lieu précis et horaires"],["slot","Créneau : heure de début, heure de fin et adresse"]],correct=fields.filter(([id])=>lastMissionData?.get(id)==="precise").length,details=fields.map(([id,label])=>`${lastMissionData?.get(id)==="precise"?"✓":"À préciser"} — ${label}`).join(" ; ");return `${correct} / 3 informations suffisamment précises. ${details}. Les informations doivent permettre au préleveur de trouver le sportif sans devoir lui téléphoner.`}},
 {title:"Changement de dernière minute",instruction:"Lis le SMS du coach, puis sélectionne les informations utiles à transmettre dans ADAMS ou Athlete Central.",render:()=>`<div class="coach-sms"><header><span>🚲</span><div><strong>Coach</strong><small>Programme des deux prochains jours</small></div></header><p>Salut Léa, voici le nouveau programme. Mardi : entraînement de 16 h 30 à 18 h 30 au vélodrome Georges-Préveral, 59 rue Pierre-Baratin à Lyon. Tu dormiras à l’Hôtel des Quais, 12 quai Perrache, chambre 308. Ton créneau sera de 20 h à 21 h dans cette chambre. Mercredi : compétition à 10 h au Palais des Sports de Gerland, puis nuit à l’Hôtel du Parc, 8 avenue des Frères-Lumière. La chambre sera confirmée plus tard. Petit-déjeuner à 7 h 30, place 6 dans le minibus et pluie annoncée.</p></div><p class="selection-help"><strong>Quelles informations sont utiles pour ta localisation ?</strong> Tu peux en sélectionner plusieurs.</p><div class="info-selection">${coachInfo.map(x=>`<label><input type="checkbox" name="coach-info" value="${x.id}"><span><small>${x.group}</small>${x.text}</span></label>`).join("")}</div>`,valid:d=>{lastMissionData=d;return d.getAll("coach-info").length>0},get feedback(){const selected=lastMissionData?.getAll("coach-info")||[],useful=coachInfo.filter(x=>x.useful),right=useful.filter(x=>selected.includes(x.id)),missed=useful.filter(x=>!selected.includes(x.id)),extra=coachInfo.filter(x=>!x.useful&&selected.includes(x.id));return `${right.length} / ${useful.length} informations utiles sélectionnées. ${missed.length?`À ajouter : ${missed.map(x=>x.text).join(" ; ")}.`:"Toutes les informations utiles ont été repérées."} ${extra.length?`À écarter : ${extra.map(x=>x.text).join(" ; ")}.`:"Aucune information personnelle inutile n’a été retenue."} Les groupes attendus sont l’hébergement précis, les entraînements, les compétitions et le créneau de 60 minutes. Les informations doivent être mises à jour dès que le changement est connu ; la chambre encore inconnue pourra être précisée dès sa confirmation.`}},
 {title:"Comprendre les manquements",instruction:"Associe chaque situation à sa conséquence possible.",render:()=>`<div class="case-list">${[["Un sportif du groupe de contrôle ne transmet pas les informations demandées.","target","Inclusion possible dans le groupe cible"],["Un sportif du groupe cible oublie de transmettre son trimestre.","filing","Manquement à la transmission possible"],["Le sportif est absent pendant son créneau déclaré.","missed","Contrôle manqué possible"]].map((x,i)=>`<label><span>${x[0]}</span><select name="case-${i}"><option value="">Conséquence…</option><option value="target">Inclusion possible dans le groupe cible</option><option value="filing">Manquement à la transmission possible</option><option value="missed">Contrôle manqué possible</option></select></label>`).join("")}</div>`,valid:d=>{lastMissionData=d;return [0,1,2].every(i=>Boolean(d.get(`case-${i}`)))},get feedback(){const cases=[["target","Groupe de contrôle sans transmission","Inclusion possible dans le groupe cible"],["filing","Trimestre non transmis par un membre du groupe cible","Manquement à la transmission possible"],["missed","Absence pendant le créneau déclaré","Contrôle manqué possible"]],correct=cases.filter((x,i)=>lastMissionData?.get(`case-${i}`)===x[0]).length,details=cases.map((x,i)=>`${lastMissionData?.get(`case-${i}`)===x[0]?"✓":"À revoir"} — ${x[1]} : ${x[2]}`).join(" ; ");return `${correct} / ${cases.length} réponses justes. ${details}. Un manquement présumé est examiné et le sportif peut présenter ses observations : une erreur ne provoque pas automatiquement une suspension.`}}
];
function show(s){if(s.id==="feedback"&&window.ProcycleanGroup)window.ProcycleanGroup.record("mission-"+step,missions[step].title,window.ProcycleanGroup.formAnswers($("#mission-form")),$("#feedback-title").textContent,[
 "Sam et Léa ont reçu une notification officielle qui déclenche leurs obligations. Alex n’a pas d’informations de localisation à transmettre dans cette mission.",
 "Les deux groupes transmettent un planning précis : hébergement, entraînements, travail ou études, compétitions et mises à jour dans ADAMS ou Athlete Central. Le groupe cible ajoute un créneau quotidien de 60 minutes.",
 "Il faut pouvoir trouver le sportif : hébergement avec adresse et chambre, entraînement avec adresse et horaires, créneau de 60 minutes avec heure de début, heure de fin et adresse précise.",
 "Transmettre les informations utiles sur l’hébergement, l’entraînement, la compétition et le créneau de 60 minutes. Mettre à jour les informations connues dès le changement, puis compléter la chambre dès sa confirmation.",
 "Groupe de contrôle sans transmission : inclusion possible dans le groupe cible. Groupe cible sans transmission du trimestre : manquement à la transmission possible. Absence pendant le créneau déclaré : contrôle manqué possible. Un manquement présumé est examiné et le sportif peut présenter ses observations ; une erreur isolée ne provoque pas automatiquement une suspension."
][step]);screens.forEach(x=>x.hidden=x!==s);s.scrollIntoView({block:"start"})}function render(){const m=missions[step],form=$("#mission-form");form.dataset.reviewed="false";$("#validate").textContent="Valider";$("#mission-message").className="";$("#mission-number").textContent=`MISSION ${step+1} SUR ${missions.length}`;$("#mission-title").textContent=m.title;$("#mission-instruction").textContent=m.instruction;$("#completion-bar").style.width=`${(step+1)/missions.length*100}%`;$("#mission-content").innerHTML=m.render();$("#mission-message").textContent="";show($("#mission"))}
$("#mission-form").onsubmit=e=>{e.preventDefault();const m=missions[step],data=new FormData(e.currentTarget);if(step===0){const selected=data.getAll("athlete");if(!selected.length){$("#mission-message").textContent="Sélectionne au moins un sportif.";return}const correct=m.valid(data);$("#feedback-title").textContent=correct?"Statuts correctement identifiés":"Regardons les notifications reçues";$("#feedback-text").innerHTML=`<p class="${correct?"feedback-success":"feedback-review"}">${correct?"✓ Sam et Léa sont bien les deux sportifs concernés.":"Sam et Léa doivent être sélectionnés, mais pas Alex."}</p><div class="status-feedback"><article><strong>Alex · Aucun groupe</strong><p>Il n’a reçu aucun courrier : il n’a pas d’informations de localisation à transmettre dans cette mission.</p></article><article><strong>Sam · Groupe de contrôle</strong><p>Le courrier de l’AFLD lui demande officiellement de transmettre ses informations.</p></article><article><strong>Léa · Groupe cible</strong><p>Sa notification officielle d’inclusion déclenche ses obligations de localisation.</p></article></div><p>${m.feedback}</p>`}else{if(!m.valid(data)){$("#mission-message").textContent="Certaines informations sont encore à préciser ou à corriger.";return}$("#feedback-title").textContent=m.title;$("#feedback-text").innerHTML=`<p>${m.feedback}</p>`}$("#continue").textContent=step===missions.length-1?"Voir le bilan":"Mission suivante";show($("#feedback"))};$("#continue").onclick=()=>{step++;step<missions.length?render():show($("#final"))};$("#start").onclick=render;

$("#mission-form").addEventListener("submit",event=>{
  if(step!==1)return;
  event.preventDefault();event.stopImmediatePropagation();
  const form=event.currentTarget,data=new FormData(form);
  if(!obligations.every((_,i)=>Boolean(data.get(`ob-${i}`)))){$("#mission-message").textContent="Classe toutes les cartes avant de vérifier.";return}
  if(form.dataset.reviewed!=="true"){
    const names={both:"Les deux groupes",target:"Groupe cible",control:"Groupe de contrôle",none:"Aucun des deux"};let correct=0;
    document.querySelectorAll(".obligation-list label").forEach((label,i)=>{const chosen=data.get(`ob-${i}`),expected=obligations[i][1],ok=chosen===expected;if(ok)correct++;label.classList.add(ok?"answer-correct":"answer-wrong");const note=document.createElement("small");note.className="inline-correction";note.textContent=ok?"✓ Bonne réponse":`Ta réponse : ${names[chosen]} · Réponse attendue : ${names[expected]}`;label.append(note);const select=label.querySelector("select");select.setAttribute("aria-readonly","true");select.style.pointerEvents="none"});
    form.dataset.reviewed="true";$("#mission-message").className="review-result";$("#mission-message").textContent=`${correct} / ${obligations.length} réponses justes. Les corrections apparaissent sous chaque carte.`;$("#validate").textContent="Voir le tableau récapitulatif";$("#mission").scrollIntoView({block:"start"});return;
  }
  $("#feedback-title").textContent="Qui doit transmettre quoi ?";$("#feedback-text").innerHTML=`<div class="obligation-table-wrap"><table class="obligation-table"><thead><tr><th>Statut</th><th>Informations à transmettre</th><th>Outil et mise à jour</th></tr></thead><tbody><tr><th>Aucun groupe</th><td>Pas d’obligation tant qu’aucune notification officielle n’est reçue.</td><td>—</td></tr><tr><th>Groupe de contrôle</th><td>Hébergement complet ; entraînements ; travail ou études ; compétitions ; informations assez précises pour être trouvé.</td><td>ADAMS ou Athlete Central, à mettre à jour dès qu’un changement est connu.</td></tr><tr><th>Groupe cible</th><td>Les mêmes informations, plus un créneau quotidien de 60 minutes à une adresse précise.</td><td>ADAMS ou Athlete Central, à mettre à jour dès qu’un changement est connu.</td></tr></tbody></table></div><p class="essential-difference"><strong>Différence essentielle :</strong> les deux groupes transmettent un planning précis ; le groupe cible ajoute le créneau quotidien de 60 minutes.</p>`;$("#continue").textContent="Mission suivante";show($("#feedback"));
},true);

$("#mission-form").addEventListener("submit",event=>{
  if(step!==3)return;
  event.preventDefault();event.stopImmediatePropagation();
  const selected=new FormData(event.currentTarget).getAll("coach-info");
  if(!selected.length){$("#mission-message").textContent="Sélectionne au moins une information dans le message du coach.";return}
  const useful=coachInfo.filter(x=>x.useful),right=useful.filter(x=>selected.includes(x.id)),missed=useful.filter(x=>!selected.includes(x.id)),extra=coachInfo.filter(x=>!x.useful&&selected.includes(x.id));
  const list=(items,empty)=>items.length?`<ul>${items.map(x=>`<li><small>${x.group}</small><span>${x.text}</span></li>`).join("")}</ul>`:`<p>${empty}</p>`;
  $("#feedback-title").textContent="Quelles informations fallait-il transmettre ?";
  $("#feedback-text").innerHTML=`<p class="mission-score">${right.length} / ${useful.length} informations utiles repérées</p><div class="info-feedback-grid"><section class="info-good"><h3>✓ Bien retenues</h3>${list(right,"Aucune information utile n’a encore été retenue.")}</section><section class="info-missed"><h3>＋ À ajouter</h3>${list(missed,"Toutes les informations utiles ont été repérées.")}</section><section class="info-extra"><h3>— À écarter</h3>${list(extra,"Aucune information inutile n’a été sélectionnée.")}</section></div><div class="expected-groups"><h3>Les groupes d’informations attendus</h3><div><article><strong>Hébergement</strong><span>Nom, adresse complète et chambre dès qu’elle est connue.</span></article><article><strong>Entraînement</strong><span>Lieu précis, adresse et horaires.</span></article><article><strong>Compétition</strong><span>Lieu, adresse, date et horaire.</span></article><article><strong>Créneau de 60 minutes</strong><span>Heure de début, heure de fin et adresse précise.</span></article></div><p><strong>À retenir :</strong> Léa met à jour ce qu’elle sait dès le changement, puis complète la chambre dès sa confirmation.</p></div>`;
  $("#continue").textContent="Mission suivante";show($("#feedback"));
},true);

$("#mission-form").addEventListener("submit",event=>{
  if(step!==4)return;
  event.preventDefault();event.stopImmediatePropagation();
  const data=new FormData(event.currentTarget),names={target:"Inclusion possible dans le groupe cible",filing:"Manquement à la transmission possible",missed:"Contrôle manqué possible"};
  if(![0,1,2].every(i=>Boolean(data.get(`case-${i}`)))){$("#mission-message").textContent="Associe une conséquence à chacune des trois situations.";return}
  const cases=[
    {expected:"target",title:"Groupe de contrôle : informations non transmises",why:"Le sportif peut notamment être inclus dans le groupe cible."},
    {expected:"filing",title:"Groupe cible : trimestre non transmis",why:"Un manquement à l’obligation de transmission peut être constaté."},
    {expected:"missed",title:"Absence pendant le créneau déclaré",why:"Un contrôle manqué peut être relevé."}
  ];
  const correct=cases.filter((item,i)=>data.get(`case-${i}`)===item.expected).length;
  $("#feedback-title").textContent="Que peut-il arriver en cas d’erreur ?";
  $("#feedback-text").innerHTML=`<p class="mission-score">${correct} / ${cases.length} réponses justes</p><div class="case-feedback">${cases.map((item,i)=>{const given=data.get(`case-${i}`),ok=given===item.expected;return `<article class="${ok?"case-correct":"case-review"}"><h3>${ok?"✓":"À revoir"} — ${item.title}</h3><p><strong>Ta réponse :</strong> ${names[given]}</p>${ok?"":`<p><strong>Réponse attendue :</strong> ${names[item.expected]}</p>`}<p class="case-explanation">${item.why}</p></article>`}).join("")}</div><aside class="nuance-note"><strong>Une conséquence n’est pas automatique</strong><p>Un manquement présumé est examiné et le sportif peut présenter ses observations. Une erreur isolée ne provoque donc pas automatiquement une suspension.</p></aside><aside class="advanced-warning"><strong>Pour le public avancé</strong><p>Une combinaison de trois manquements sur une période continue de douze mois peut constituer une violation des règles antidopage et entraîner une procédure disciplinaire.</p></aside>`;
  $("#continue").textContent="Voir le bilan";show($("#feedback"));
},true);

$("#mission-form").addEventListener("submit",event=>{
  if(step!==2)return;
  event.preventDefault();event.stopImmediatePropagation();
  const data=new FormData(event.currentTarget),fields=[
    {id:"hotel",title:"Hébergement",expected:"Hôtel du Vélodrome, 24 rue du Stade, chambre 214",why:"Le nom seul de l’hôtel ne suffit pas : l’adresse complète et la chambre permettent de trouver Léa."},
    {id:"training",title:"Entraînement",expected:"9 h à 12 h, Vélodrome, 8 avenue de la Piste",why:"Le lieu précis, son adresse et les horaires doivent être indiqués."},
    {id:"slot",title:"Créneau de 60 minutes",expected:"18 h à 19 h, Hôtel du Vélodrome, chambre 214",why:"Le créneau exige une heure de début, une heure de fin et une adresse précise."}
  ];
  if(!fields.every(x=>Boolean(data.get(x.id)))){$("#mission-message").textContent="Choisis une proposition pour chacune des trois informations.";return}
  const correct=fields.filter(x=>data.get(x.id)==="precise").length;
  $("#feedback-title").textContent="Le planning est-il assez précis ?";
  $("#feedback-text").innerHTML=`<p class="mission-score">${correct} / ${fields.length} informations suffisamment précises</p><div class="precision-feedback">${fields.map(item=>{const select=document.querySelector(`[name="${item.id}"]`),given=select.options[select.selectedIndex].text,ok=data.get(item.id)==="precise";return `<article class="${ok?"precision-correct":"precision-review"}"><h3>${ok?"✓ Suffisamment précis":"À préciser"} — ${item.title}</h3><p><strong>Ton choix :</strong> ${given}</p>${ok?"":`<p><strong>Information attendue :</strong> ${item.expected}</p>`}<p class="precision-explanation">${item.why}</p></article>`}).join("")}</div><aside class="precision-rule"><strong>La règle à retenir</strong><p>Les informations doivent permettre à la personne chargée du contrôle de trouver le sportif sans devoir l’appeler pour demander des précisions.</p></aside>`;
  $("#continue").textContent="Mission suivante";show($("#feedback"));
},true);


// Synchronisation de ce même parcours lorsqu’il est ouvert dans une séance.
window.ProcycleanGroup?.register({
 snapshot:()=>({state:{step,screen:screens.find(x=>!x.hidden)?.id},progress:!$("#final").hidden?100:(step+($("#feedback").hidden?0:1))/missions.length*95,complete:!$("#final").hidden}),
 restore:s=>{step=s.step+(s.screen==="feedback"?1:0);if(step>=missions.length)show($("#final"));else if(s.screen!=="intro")render();}
});
