import{initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import{getAuth,onAuthStateChanged,signInAnonymously}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import{getDatabase,ref,get,onValue,runTransaction,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-database.js";
import{QUESTIONS,answerRecord,answerLabel}from"../quiz-data.js";
import{AFLD_URL,MEDICATION_EXERCISES,STATUS_OPTIONS,medicationAnswerRecord}from"../medication-data.js";
const config={apiKey:"AIzaSyCX6Y_ImG1YNEMY19pSSl4FxaHKqo72B3s",authDomain:"activites-procyclean.firebaseapp.com",databaseURL:"https://activites-procyclean-default-rtdb.europe-west1.firebasedatabase.app/",projectId:"activites-procyclean",storageBucket:"activites-procyclean.firebasestorage.app",messagingSenderId:"900663423725",appId:"1:900663423725:web:bc51501dcf653bfd1052e4"};
const auth=getAuth(initializeApp(config)),database=getDatabase(),$=selector=>document.querySelector(selector),screens=["loading","error","waiting","quiz","step-two","medication","final"].map(id=>$("#"+id));
let user,session,code,selected=null,busy=false,stopSession=null,completionWritten=false;
function show(screen){screens.forEach(item=>item.hidden=item!==screen);requestAnimationFrame(()=>screen.scrollIntoView({behavior:"smooth",block:"center",inline:"nearest"}))}
function fail(message){$("#error-message").textContent=message;show($("#error"))}
function authUser(){return new Promise((resolve,reject)=>{const stop=onAuthStateChanged(auth,async current=>{try{if(current?.isAnonymous){stop();resolve(current)}else{const result=await signInAnonymously(auth);stop();resolve(result.user)}}catch(error){stop();reject(error)}},reject)})}
async function register(){const result=await runTransaction(ref(database,"sessions/"+code),value=>{if(!value||value.activity!=="labo-interdictions")return;value.participants||={};const old=value.participants[user.uid];if(old?.participantNumber){old.quizAnswers||={};old.medicationAnswers||={};return value}const number=(value.nextParticipantNumber||0)+1;value.nextParticipantNumber=number;value.participants[user.uid]={participantNumber:number,joinedAt:serverTimestamp(),status:"waiting",quizAnswers:{},medicationAnswers:{}};return value});if(!result.committed)throw Error("Inscription impossible")}
function renderQuestion(participant){const index=Math.min(Number(session.currentQuestion)||0,QUESTIONS.length-1),question=QUESTIONS[index],record=participant.quizAnswers?.[question.id],revealed=!!session.feedbackRevealed;selected=null;$("#question-count").textContent="QUESTION "+(index+1)+" / "+QUESTIONS.length;$("#answer-status").textContent=record?"Réponse enregistrée":"";$("#progress-bar").style.width=((index+1)/QUESTIONS.length*100)+"%";$("#situation").hidden=!question.situation;$("#situation").textContent=question.situation||"";$("#question").textContent=question.statement;$("#answers").replaceChildren(...question.answers.map(answer=>{const button=document.createElement("button");button.type="button";button.className="quiz-answer";button.textContent=answer.label;button.disabled=!!record;button.classList.toggle("selected",record?.answer===answer.id);button.onclick=()=>{selected=answer.id;document.querySelectorAll("#answers .quiz-answer").forEach(item=>item.classList.toggle("selected",item===button));$("#validate").disabled=false};return button}));$("#validation-actions").hidden=!!record;$("#validate").disabled=!selected;$("#response-waiting").hidden=!record||revealed;$("#feedback").hidden=!record||!revealed;if(record&&revealed){$("#feedback").className="quiz-feedback "+(record.correct?"correct":"rethink");$("#feedback-title").textContent=record.correct?"✓ Bonne réponse":"✗ Pas tout à fait";$("#feedback-text").textContent=record.correct?question.feedback:"La bonne réponse était « "+answerLabel(question,question.correct)+" ». "+question.feedback}show($("#quiz"))}
function renderMedication(participant){const index=Math.min(Number(session.currentMedication)||0,MEDICATION_EXERCISES.length-1),exercise=MEDICATION_EXERCISES[index],record=participant.medicationAnswers?.[exercise.id],revealed=!!session.medicationFeedbackRevealed;selected=null;$("#medication-level").textContent=exercise.level;$("#medication-count").textContent="RECHERCHE "+(index+1)+" / "+MEDICATION_EXERCISES.length;$("#medication-progress").style.width=((index+1)/MEDICATION_EXERCISES.length*100)+"%";$("#medication-name").textContent=exercise.name;$("#medication-instruction").textContent=exercise.instruction;$("#open-afld").href=AFLD_URL;$("#medication-options").replaceChildren(...STATUS_OPTIONS.map(option=>{const button=document.createElement("button");button.type="button";button.className="quiz-answer";button.textContent=option.label;button.disabled=!!record;button.classList.toggle("selected",record?.answer===option.id);button.onclick=()=>{selected=option.id;document.querySelectorAll("#medication-options .quiz-answer").forEach(item=>item.classList.toggle("selected",item===button));$("#validate-medication").disabled=false};return button}));$("#medication-validation").hidden=!!record;$("#validate-medication").disabled=!selected;$("#medication-waiting").hidden=!record||revealed;$("#medication-feedback").hidden=!record||!revealed;if(record&&revealed){const expected=STATUS_OPTIONS.find(option=>option.id===exercise.expected)?.label;$("#medication-feedback").className="quiz-feedback "+(record.correct?"correct":"rethink");$("#medication-feedback-title").textContent=record.correct?"✓ Résultat bien lu":"✗ Pas tout à fait";$("#medication-feedback-text").textContent=record.correct?exercise.feedback:"Le statut à repérer était « "+expected+" ». "+exercise.feedback;$("#result-name").textContent=exercise.name;$("#result-route").textContent=exercise.route;$("#result-status").textContent=exercise.officialStatus}show($("#medication"))}
async function markComplete(){if(completionWritten)return;completionWritten=true;try{await runTransaction(ref(database,"sessions/"+code+"/participants/"+user.uid),participant=>participant?{...participant,status:"completed",activityCompletedAt:Date.now()}:participant)}catch(error){console.error(error)}}
function render(value){session=value;const participant=value.participants?.[user.uid];if(!participant)return;$("#participant-label").textContent="Participant "+participant.participantNumber;if(value.status==="waiting"){show($("#waiting"));return}if(value.status==="final"||value.status==="closed"){show($("#final"));markComplete();return}if(value.phase==="medicationIntro"){show($("#step-two"));return}if(value.phase==="medications"){renderMedication(participant);return}renderQuestion(participant)}
$("#validate").onclick=async()=>{if(!selected||busy)return;const question=QUESTIONS[Math.min(Number(session.currentQuestion)||0,QUESTIONS.length-1)],record=answerRecord(question,selected);busy=true;try{await runTransaction(ref(database,"sessions/"+code+"/participants/"+user.uid+"/quizAnswers/"+question.id),current=>current||{...record,answeredAt:Date.now()})}catch(error){console.error(error)}finally{busy=false}};
$("#validate-medication").onclick=async()=>{if(!selected||busy)return;const exercise=MEDICATION_EXERCISES[Math.min(Number(session.currentMedication)||0,MEDICATION_EXERCISES.length-1)],record=medicationAnswerRecord(exercise,selected);busy=true;try{await runTransaction(ref(database,"sessions/"+code+"/participants/"+user.uid+"/medicationAnswers/"+exercise.id),current=>current||{...record,answeredAt:Date.now()})}catch(error){console.error(error)}finally{busy=false}};
$("#copy-name").onclick=async()=>{try{await navigator.clipboard.writeText(MEDICATION_EXERCISES[Math.min(Number(session.currentMedication)||0,MEDICATION_EXERCISES.length-1)].name);$("#copy-name").textContent="Nom copié ✓"}catch{$("#copy-name").textContent="Sélectionne puis copie le nom"}};
$("#show-afld").onclick=()=>{$("#afld-embed").hidden=false;requestAnimationFrame(()=>$("#afld-embed").scrollIntoView({behavior:"smooth",block:"start"}))};
$("#hide-afld").onclick=()=>{$("#afld-embed").hidden=true;$("#show-afld").focus()};
let displayedMedication="";
new MutationObserver(()=>{const name=$("#medication-name").textContent;if(!name||name===displayedMedication)return;displayedMedication=name;$("#afld-embed").hidden=true;$("#copy-name").textContent="Copier le nom";const frame=$(".afld-embed iframe");frame.src="about:blank";requestAnimationFrame(()=>{frame.src=AFLD_URL})}).observe($("#medication-name"),{childList:true});
async function load(){code=String(new URLSearchParams(location.search).get("session")||"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6);if(code.length!==6){fail("Code de session incorrect.");return}try{user=await authUser();const sessionRef=ref(database,"sessions/"+code),snapshot=await get(sessionRef);if(!snapshot.exists()||snapshot.val().activity!=="labo-interdictions"){fail("Session indisponible.");return}await register();stopSession=onValue(sessionRef,snapshot=>snapshot.exists()?render(snapshot.val()):fail("Session supprimée."))}catch(error){console.error(error);fail("Connexion impossible.")}}
addEventListener("pagehide",()=>stopSession?.());load();
