import{DEFINITION,OPENING_CHOICES,CROSSROAD,CROSSROAD_ZONES,DOSSIER_CARDS,CRITERIA,TIMELINE,SOURCED_RULES,shuffle}from"../../aut-bon-parcours/aut-data.js";
const $=s=>document.querySelector(s),screenIds=["intro","chapter-one","definition","crossroad","levels","dossier","committee","criteria","granted","emergency","timeline","retro-info","final"],screens=screenIds.map(id=>$("#"+id)),storageKey="procyclean-aut-bon-parcours-v1";let state={screen:"intro",crossroad:{},dossier:[],criteria:{},timeline:shuffle(TIMELINE)},selected=null;
try{const saved=JSON.parse(localStorage.getItem(storageKey));if(saved?.screen)state={...state,...saved}}catch{}const save=()=>localStorage.setItem(storageKey,JSON.stringify(state));
function show(id,track=1){screens.forEach(s=>s.hidden=s.id!==id);state.screen=id;save();document.querySelectorAll("[data-track]").forEach((x,i)=>{x.classList.toggle("done",i+1<track);x.classList.toggle("active",i+1===track)});requestAnimationFrame(()=>$("#"+id).scrollIntoView({behavior:"smooth",block:"center"}))}
function choiceButtons(parent,choices,onSelect){parent.replaceChildren(...choices.map(choice=>{const b=document.createElement("button");b.className="choice-card";b.textContent=choice.label;b.onclick=()=>{selected=choice.id;parent.querySelectorAll("button").forEach(x=>x.classList.toggle("selected",x===b));onSelect?.()};return b}))}
choiceButtons($("#opening-choices"),OPENING_CHOICES,()=>$("#validate-opening").disabled=false);$("#definition-text").textContent=DEFINITION.educationalText;$("#national-rule").textContent=SOURCED_RULES.national.educationalText;$("#infranational-rule").textContent=SOURCED_RULES.infranational.educationalText;
$("#start").onclick=()=>show("chapter-one",1);$("#validate-opening").onclick=()=>{const ok=selected==="verify";$("#opening-feedback").className="feedback "+(ok?"good":"bad");$("#opening-feedback").innerHTML=ok?"<strong>✓ Le bon réflexe</strong><p>La santé reste prioritaire, mais la démarche antidopage doit être vérifiée.</p>":"<strong>Pas tout à fait</strong><p>Il ne faut ni refuser automatiquement un soin nécessaire, ni ignorer les règles : Noa doit se soigner et vérifier la démarche.</p>";$("#opening-feedback").hidden=false;$("#validate-opening").hidden=true;$("#show-definition").hidden=false};$("#show-definition").onclick=()=>show("definition",3);$("#go-crossroad").onclick=()=>{renderCrossroad();show("crossroad",3)};
function card(text,id){const b=document.createElement("button");b.className="drag-card";b.textContent=text;b.onclick=event=>{event.stopPropagation();selected=selected===id?null:id;renderCrossroad()};b.classList.toggle("selected",selected===id);return b}
function renderCrossroad(){const zones=$("#crossroad-zones");zones.replaceChildren(...CROSSROAD_ZONES.map(zone=>{const div=document.createElement("div");div.className="drop-zone";div.dataset.zone=zone.id;div.innerHTML=`<strong>${zone.label}</strong><span></span>`;CROSSROAD.filter(item=>state.crossroad[item.id]===zone.id).forEach(item=>div.querySelector("span").append(card(item.text,item.id)));div.onclick=()=>{if(!selected)return;state.crossroad[selected]=zone.id;selected=null;save();renderCrossroad()};return div}));$("#crossroad-bank").replaceChildren(...CROSSROAD.filter(item=>!state.crossroad[item.id]).map(item=>card(item.text,item.id)));$("#validate-crossroad").disabled=Object.keys(state.crossroad).length!==CROSSROAD.length}
$("#validate-crossroad").onclick=()=>{const wrong=CROSSROAD.filter(item=>state.crossroad[item.id]!==item.answer);$("#crossroad-feedback").className="feedback "+(wrong.length?"bad":"good");$("#crossroad-feedback").innerHTML=wrong.length?`<strong>${CROSSROAD.length-wrong.length}/${CROSSROAD.length} situations bien placées</strong><ul>${wrong.map(x=>`<li>${x.feedback}</li>`).join("")}</ul>`:"<strong>✓ Les deux chemins sont compris</strong><p>Une demande rétroactive répond à des situations prévues par les règles : ce n’est pas une solution à un simple oubli.</p>";$("#crossroad-feedback").hidden=false;$("#validate-crossroad").hidden=true;$("#show-levels").hidden=false};$("#show-levels").onclick=()=>show("levels",3);$("#begin-dossier").onclick=()=>{renderDossier();show("dossier",4)};
function dossierCard(item){const b=document.createElement("button");b.className="drag-card dossier-card";b.textContent=item.label;b.onclick=()=>{state.dossier=state.dossier.includes(item.id)?state.dossier.filter(id=>id!==item.id):[...state.dossier,item.id];save();renderDossier()};return b}function renderDossier(){const chosen=DOSSIER_CARDS.filter(x=>state.dossier.includes(x.id));$("#folder-content").replaceChildren(...chosen.map(x=>{const b=dossierCard(x);b.classList.add("in-folder");return b}));$("#dossier-bank").replaceChildren(...DOSSIER_CARDS.filter(x=>!state.dossier.includes(x.id)).map(dossierCard));$("#dossier-count").textContent=`${chosen.length} élément${chosen.length>1?"s":""}`;$("#validate-dossier").disabled=!state.dossier.length}
$("#validate-dossier").onclick=()=>{const chosen=DOSSIER_CARDS.filter(x=>state.dossier.includes(x.id)),missing=DOSSIER_CARDS.filter(x=>x.useful&&!state.dossier.includes(x.id)),distractors=chosen.filter(x=>!x.useful),ok=!missing.length&&!distractors.length;$("#dossier-feedback").className="feedback "+(ok?"good":"bad");$("#dossier-feedback").innerHTML=ok?"<strong>✓ Le dossier donne au comité des éléments médicaux utiles</strong><p>La liste exacte dépend de la pathologie : l’objectif est de documenter le diagnostic et la nécessité du traitement.</p>":`<strong>Le dossier doit rester médical et suffisamment complet</strong>${missing.length?`<p>Éléments utiles encore absents : ${missing.map(x=>x.label).join(", ")}.</p>`:""}${distractors.length?`<p>Éléments qui n’aident pas l’examen médical : ${distractors.map(x=>x.label).join(", ")}.</p>`:""}`;$("#dossier-feedback").hidden=false;$("#validate-dossier").hidden=true;$("#show-committee").hidden=false};$("#show-committee").onclick=()=>show("committee",5);$("#begin-criteria").onclick=()=>{renderCriteria();show("criteria",5)};
function renderCriteria(){$("#criteria-grid").replaceChildren(...CRITERIA.map(item=>{const a=document.createElement("article");a.className="criterion"+(state.criteria[item.id]===item.answer?" complete":"");a.innerHTML=`<header><i class="light"></i><div><h3>${item.title}</h3><p>${item.evidence}</p></div></header><div class="toggle-row"><button class="secondary" data-value="met">Rempli</button><button class="secondary" data-value="missing">Pas encore démontré</button></div>`;a.querySelectorAll("button").forEach(b=>{b.classList.toggle("selected",state.criteria[item.id]===b.dataset.value);b.onclick=()=>{state.criteria[item.id]=b.dataset.value;save();renderCriteria()}});return a}));$("#validate-criteria").disabled=Object.keys(state.criteria).length!==CRITERIA.length}
$("#validate-criteria").onclick=()=>{const wrong=CRITERIA.filter(x=>state.criteria[x.id]!==x.answer);if(wrong.length){$("#criteria-feedback").className="feedback bad";$("#criteria-feedback").innerHTML=`<strong>${CRITERIA.length-wrong.length}/${CRITERIA.length} évaluations justes</strong><p>${wrong.map(x=>`${x.title} : ${x.answer==="met"?"le dossier le démontre":"ce n’est pas encore démontré"}.`).join(" ")}</p><p>Le dossier est complété avec l’explication sur l’absence d’alternative raisonnable.</p>`;state.criteria.alternative="met";save();renderCriteria();$("#criteria-feedback").hidden=false;$("#validate-criteria").textContent="Soumettre le dossier complété"}else show("granted",5)};$("#begin-emergency").onclick=()=>show("emergency",2);
$("#emergency-choices").onclick=e=>{const b=e.target.closest("button");if(!b)return;selected=b.dataset.answer;$("#emergency-choices").querySelectorAll("button").forEach(x=>x.classList.toggle("selected",x===b));$("#validate-emergency").disabled=false};$("#validate-emergency").onclick=()=>{const ok=selected==="care";$("#emergency-feedback").className="feedback "+(ok?"good":"bad");$("#emergency-feedback").innerHTML=ok?"<strong>✓ Les soins nécessaires sont prioritaires</strong><p>Une AUT à effet rétroactif peut ensuite être demandée si les conditions prévues sont réunies.</p>":"<strong>En urgence, il ne faut pas retarder les soins nécessaires</strong><p>La démarche rétroactive existe précisément pour certaines situations prévues par les règles.</p>";$("#emergency-feedback").hidden=false;$("#validate-emergency").hidden=true;$("#begin-timeline").hidden=false};$("#begin-timeline").onclick=()=>{renderTimeline();show("timeline",4)};
function renderTimeline(){$("#timeline-list").replaceChildren(...state.timeline.map((text,index)=>{const li=document.createElement("li");li.className="timeline-item"+(selected===index?" selected":"");li.textContent=`${index+1}. ${text}`;li.onclick=()=>{if(selected===null){selected=index;renderTimeline()}else{[state.timeline[selected],state.timeline[index]]=[state.timeline[index],state.timeline[selected]];selected=null;save();renderTimeline()}};return li}))}$("#validate-timeline").onclick=()=>{const ok=TIMELINE.every((x,i)=>state.timeline[i]===x);$("#timeline-feedback").className="feedback "+(ok?"good":"bad");$("#timeline-feedback").innerHTML=ok?"<strong>✓ La chronologie est juste</strong><p>Rétroactive ne signifie pas automatique : un dossier est constitué et le comité rend une décision.</p>":`<strong>Pas encore dans le bon ordre</strong><p>Ordre attendu : ${TIMELINE.join(" → ")}.</p>`;$("#timeline-feedback").hidden=false;if(ok){$("#validate-timeline").hidden=true;$("#show-retro-info").hidden=false}};$("#show-retro-info").onclick=()=>show("retro-info",5);$("#show-final").onclick=()=>show("final",5);$("#restart").onclick=()=>{localStorage.removeItem(storageKey);location.reload()};
document.addEventListener("click",e=>{const a=e.target.closest("a");if(a&&new URL(a.href,location.href).pathname.endsWith("/activites/individuel/index.html"))localStorage.removeItem(storageKey)},true);
if(state.screen!=="intro"){
  if(state.screen==="crossroad")renderCrossroad();
  if(state.screen==="dossier")renderDossier();
  if(state.screen==="criteria")renderCriteria();
  if(state.screen==="timeline")renderTimeline();
  show(state.screen,1);
}
