const $=s=>document.querySelector(s);let step=0;
const locks=[
 {title:"Le traitement est nécessaire",prompt:"Que doit montrer le dossier médical de Noa ?",text:"Le sportif a réellement besoin du traitement pour protéger ou retrouver sa santé.",choices:["Le traitement est le plus rapide à utiliser.","Le sportif a réellement besoin du traitement pour sa santé.","Le traitement est conseillé par son entraîneur.","Le produit est disponible sans ordonnance."],answer:1},
 {title:"Pas d’avantage supplémentaire",prompt:"Quel effet le traitement peut-il avoir sur la performance ?",text:"Le traitement soigne sans rendre le sportif plus performant que son état normal de bonne santé.",choices:["Il peut améliorer fortement ses performances pendant une compétition.","Il peut lui donner un avantage si la dose reste faible.","Il doit seulement lui permettre de retrouver son état normal de santé.","Son effet sur la performance n’a pas besoin d’être étudié."],answer:2},
 {title:"Pas d’alternative autorisée adaptée",prompt:"Que faut-il vérifier concernant les autres traitements ?",text:"Aucun autre traitement autorisé et raisonnable ne peut remplacer celui-ci.",choices:["Qu’aucun autre traitement autorisé et adapté ne peut le remplacer.","Que Noa préfère personnellement ce traitement.","Que ce traitement est utilisé par d’autres sportifs.","Que l’autre traitement coûte plus cher."],answer:0},
 {title:"Pas d’usage interdit antérieur à l’origine du besoin",prompt:"Quelle doit être l’origine du besoin médical ?",text:"Le besoin de traitement ne doit pas résulter de l’usage antérieur d’une substance ou méthode interdite sans AUT.",choices:["Il peut résulter d’un produit interdit pris sans AUT si le sportif le regrette.","Il peut résulter d’un produit interdit lorsque personne ne l’a découvert.","Son origine importe peu dès lors qu’un médecin rédige une ordonnance.","Il ne doit pas résulter de l’usage antérieur d’une substance ou méthode interdite sans AUT."],answer:3}
];
const steps=[
 {label:"INTRODUCTION",render:()=>`<div class="case"><span>🩺</span><div><h2>Noa doit utiliser un traitement médical</h2><p>Ce traitement contient une substance interdite. Doit-il refuser de se soigner ?</p></div></div>${radios("care",["Oui, un sportif ne peut jamais utiliser de substance interdite.","Non, il peut prendre le traitement sans rien vérifier.","Non, il doit se soigner et vérifier si une AUT est nécessaire."])}`,read:()=>{const v=checked("care");return v===null?null:{correct:v===2,title:"La santé reste prioritaire",html:`<p>La santé du sportif reste prioritaire. Une AUT peut permettre l’utilisation d’un traitement médical nécessaire contenant une substance ou une méthode normalement interdite.</p><p class="correct-answer"><strong>Réponse recommandée :</strong> se soigner et vérifier si une AUT est nécessaire.</p>`}}},
 {label:"ÉTAPE 1 · COMPRENDRE L’AUT",render:()=>`<h2>Dans quelle situation parle-t-on d’une AUT ?</h2><p>Complète la définition en choisissant la suite logique de chaque phrase.</p><div class="definition-builder"><label><strong>1. Une AUT permet à un sportif…</strong><select name="definition-1"><option value="">Choisir…</option><option value="performance">d’améliorer volontairement ses performances</option><option value="correct">de suivre un traitement médical dont il a réellement besoin</option><option value="libre">d’utiliser librement n’importe quel produit</option></select></label><label><strong>2. Elle peut être nécessaire lorsque ce traitement…</strong><select name="definition-2"><option value="">Choisir…</option><option value="conseil">a été conseillé par un membre de l’équipe</option><option value="correct">contient une substance ou une méthode interdite</option><option value="prescription">a simplement été prescrit par un médecin</option></select></label><label><strong>3. L’utilisation peut être autorisée à condition que…</strong><select name="definition-3"><option value="">Choisir…</option><option value="automatic">l’autorisation soit accordée automatiquement</option><option value="once">le produit ne soit utilisé qu’une seule fois</option><option value="correct">les critères prévus soient remplis et le dossier examiné</option></select></label></div>`,read:()=>{const values=[1,2,3].map(i=>document.querySelector(`[name="definition-${i}"]`).value);if(values.some(x=>x===""))return null;const correct=values.filter(x=>x==="correct").length;return{correct:correct===3,title:"La logique d’une AUT",html:`<p class="result-count">${correct} / 3 parties correctement complétées</p><div class="definition-logic"><span>Traitement médical nécessaire</span><i>+</i><span>Substance ou méthode interdite</span><i>+</i><span>Critères remplis et dossier examiné</span></div><p class="definition-result">Une AUT est une autorisation permettant à un sportif de suivre un traitement médical nécessaire contenant une substance ou une méthode interdite, lorsque les critères prévus sont remplis.</p><p><strong>À retenir :</strong> une prescription médicale ne vaut pas automatiquement AUT. L’autorisation permet de se soigner dans un cadre précis ; elle n’autorise pas à se doper.</p>`}}},
 {label:"ÉTAPE 2 · AVANT OU APRÈS ?",render:()=>`<h2>Le statut du sportif détermine le bon chemin</h2><p>Pour chaque profil, indique à quel moment la demande d’AUT doit être déposée.</p><div class="paths"><article><header>Noa est sportif de haut niveau (SHN)</header><p>Son médecin lui prescrit un traitement contenant une substance interdite.</p>${radios("prior",["Déposer une demande d’AUT avant de commencer le traitement.","Commencer le traitement puis demander systématiquement une AUT rétroactive.","Une ordonnance suffit : aucune demande n’est nécessaire."])}</article><article><header>Noa n’est pas sportif de haut niveau</header><p>Son médecin lui prescrit également un traitement contenant une substance interdite.</p>${radios("retro",["Déposer obligatoirement une demande avant le traitement.","Conserver les justificatifs médicaux et demander une AUT rétroactive si cela devient nécessaire.","Arrêter définitivement de se soigner."])}</article></div>`,read:()=>{const a=checked("prior"),b=checked("retro");if(a===null||b===null)return null;const correct=(a===0?1:0)+(b===1?1:0);return{correct:correct===2,title:"Le statut détermine le moment de la demande",html:`<p class="result-count">${correct} / 2 profils correctement orientés</p><div class="comparison"><article><h3>Sportif SHN</h3><p><strong>AUT préalable :</strong> la demande doit être déposée et l’autorisation obtenue avant d’utiliser la substance ou la méthode interdite.</p></article><article><h3>Sportif non-SHN</h3><p><strong>AUT rétroactive :</strong> il conserve ses documents médicaux et dépose une demande si la situation l’exige, notamment après un contrôle.</p></article></div><p class="nuance"><strong>Le bon réflexe :</strong> vérifier son statut et les règles applicables avant toute compétition. Dans tous les cas, une ordonnance ne remplace pas une AUT et l’accord n’est jamais automatique.</p>`}}},
 {label:"ÉTAPE 3 · LES QUATRE VERROUS",render:()=>`<h2>Ouvre les quatre verrous du dossier</h2><p>Pour chaque verrou, choisis le seul élément qui correspond au critère d’une AUT.</p><div class="vault"><div class="vault-door">DOSSIER DE NOA</div><div class="lock-list">${locks.map((lock,i)=>`<label><span>🔒 Verrou ${i+1}</span><strong>${lock.prompt}</strong><select name="lock-${i}"><option value="">Choisir une réponse…</option>${lock.choices.map((choice,j)=>`<option value="${j}">${choice}</option>`).join("")}</select></label>`).join("")}</div></div>`,read:()=>{const values=locks.map((_,i)=>document.querySelector(`[name="lock-${i}"]`).value);if(values.some(x=>x===""))return null;const correct=values.filter((x,i)=>+x===locks[i].answer).length;return{correct:correct===4,title:"Les quatre critères d’une AUT",html:`<p class="result-count">${correct} / 4 verrous correctement ouverts</p><div class="lock-feedback">${locks.map((x,i)=>`<article><span>${+values[i]===x.answer?"🔓":"🔒"}</span><div><strong>Verrou ${i+1} — ${x.title}</strong><p>${+values[i]===x.answer?"Bonne réponse. ":"La réponse attendue était : « "+x.choices[x.answer]+" ». "}${x.text}</p></div></article>`).join("")}</div><p class="warning"><strong>Attention :</strong> réunir ces éléments dans le jeu ne signifie pas « AUT accordée ». Seul le comité d’experts examine le véritable dossier et rend une décision.</p>`}}}
];
function radios(name,items){return `<div class="radio-list">${items.map((x,i)=>`<label><input type="radio" name="${name}" value="${i}"><span>${x}</span></label>`).join("")}</div>`}function checked(name){const x=document.querySelector(`[name="${name}"]:checked`);return x?+x.value:null}function render(){const s=steps[step];$("#progress-label").textContent=s.label;$("#progress-count").textContent=`${step+1} / ${steps.length}`;$("#progress-bar").style.width=`${(step+1)/steps.length*100}%`;$("#step-content").innerHTML=s.render();$("#form-message").textContent="";$("#activity").hidden=false;$("#feedback").hidden=true;$("#activity").scrollIntoView({block:"start"})}
$("#validate").onclick=()=>{const result=steps[step].read();if(!result){$("#form-message").textContent="Choisis au moins une réponse avant de valider.";return}window.ProcycleanGroup?.record("etape-"+step,steps[step].label,window.ProcycleanGroup.formAnswers($("#step-content")),result.title,[
 "La santé reste prioritaire. Une AUT peut permettre l’utilisation d’un traitement médical nécessaire contenant une substance ou une méthode normalement interdite.",
 "Une AUT est une autorisation permettant à un sportif de suivre un traitement médical nécessaire contenant une substance ou une méthode interdite, lorsque les critères prévus sont remplis et le dossier examiné. Une prescription médicale ne vaut pas automatiquement AUT.",
 "Le statut du sportif détermine le moment de la demande : AUT préalable pour le sportif SHN ; conservation des justificatifs et demande rétroactive si la situation l’exige pour le sportif non-SHN. Vérifier son statut et les règles applicables. Une ordonnance ne remplace pas une AUT et l’accord n’est jamais automatique.",
 locks.map(lock=>lock.title+" : "+lock.text).join(" ")+" Seul le comité d’experts examine le véritable dossier et rend une décision."
][step],result.correct);$("#feedback-status").className=`feedback-status ${result.correct?"correct":"review"}`;$("#feedback-status").textContent=result.correct?"✓ Bonne réponse":"Correction";$("#feedback-title").textContent=result.title;$("#feedback-content").innerHTML=result.html;$("#continue").textContent=step===steps.length-1?"Voir la synthèse":"Continuer";$("#activity").hidden=true;$("#feedback").hidden=false;$("#feedback").scrollIntoView({block:"start"})};$("#continue").onclick=()=>{step++;if(step<steps.length)render();else{$("#feedback").hidden=true;$("#final").hidden=false;$("#final").scrollIntoView({block:"start"})}};render();


// Synchronisation de ce même parcours lorsqu’il est ouvert dans une séance.
window.ProcycleanGroup?.register({
 snapshot:()=>({state:{step,feedback:!$("#feedback").hidden},progress:$("#final").hidden?(step+($("#feedback").hidden?0:1))/steps.length*95:100,complete:!$("#final").hidden}),
 restore:s=>{step=s.step+(s.feedback?1:0);if(step>=steps.length){$("#activity").hidden=true;$("#feedback").hidden=true;$("#final").hidden=false;}else render();}
});
