export const REGULATORY_META={lastChecked:"2026-08-31",jurisdiction:"France",primarySource:"https://www.afld.fr/la-lutte-antidopage/education-et-prevention/aut/",legalSource:"https://www.legifrance.gouv.fr/codes/id/LEGISCTA000026505151",internationalSource:"https://www.wada-ama.org/sites/default/files/2022-09/standard_international_pour_lautorisation_dusage_a_des_fins_therapeutiques_siaut_2023_0.pdf",reviewBefore:"2027-01-01"};
export const DEFINITION={educationalText:"Une AUT peut permettre à un sportif d’utiliser, pour des raisons médicales, un traitement nécessitant une substance ou une méthode normalement interdite.",regulatoryText:"Une AUT est une autorisation spéciale permettant de suivre un traitement nécessitant une substance ou une méthode interdite pour un état pathologique diagnostiqué. Elle ne tient pas lieu de prescription.",source:REGULATORY_META.primarySource,lastChecked:REGULATORY_META.lastChecked};
export const OPENING_CHOICES=[{id:"refuse",label:"Je refuse forcément le traitement."},{id:"ignore",label:"Je prends le traitement sans me poser de question."},{id:"verify",label:"Je me soigne, mais je vérifie quelle démarche antidopage est nécessaire."}];
export const CROSSROAD=[
 {id:"known-national",text:"Un sportif de niveau national sait plusieurs semaines avant une compétition qu’il devra suivre ce traitement.",answer:"prior",feedback:"La situation peut être anticipée : la demande préalable est la bonne démarche."},
 {id:"emergency",text:"Un sportif doit être traité immédiatement à la suite d’une urgence médicale.",answer:"retro",feedback:"Les soins nécessaires sont prioritaires. Une demande rétroactive peut ensuite être examinée si les conditions sont réunies."},
 {id:"exceptional",text:"Des circonstances exceptionnelles ont réellement empêché le sportif de déposer sa demande à temps.",answer:"retro",feedback:"Une impossibilité réelle fait partie des situations pouvant permettre l’examen d’une demande rétroactive."},
 {id:"forgot",text:"Le sportif savait depuis plusieurs semaines qu’une demande préalable était nécessaire, mais il a préféré attendre.",answer:"not-valid",feedback:"Un choix d’attendre n’est pas le fonctionnement normal d’une AUT rétroactive."}
];
export const CROSSROAD_ZONES=[{id:"prior",label:"AUT préalable"},{id:"retro",label:"AUT à effet rétroactif possible"},{id:"not-valid",label:"Ce n’est pas une justification"}];
export const DOSSIER_CARDS=[
 {id:"diagnosis",label:"Diagnostic médical étayé",useful:true},{id:"history",label:"Historique médical pertinent",useful:true},{id:"exams",label:"Résultats d’examens pertinents",useful:true},{id:"laboratory",label:"Analyses de laboratoire si nécessaires",useful:true},{id:"imaging",label:"Imagerie si pertinente",useful:true},{id:"treatment",label:"Informations précises sur le traitement",useful:true},{id:"justification",label:"Justification médicale",useful:true},{id:"alternatives",label:"Évaluation des alternatives thérapeutiques",useful:true},
 {id:"ranking",label:"Classement sportif",useful:false},{id:"wins",label:"Nombre de victoires",useful:false},{id:"sponsor",label:"Contrat avec un sponsor",useful:false},{id:"followers",label:"Nombre d’abonnés",useful:false},{id:"teammate",label:"Avis d’un coéquipier",useful:false}
];
export const CRITERIA=[
 {id:"medical",title:"Besoin médical réel",educationalText:"Le traitement est nécessaire pour une affection médicale diagnostiquée.",regulatoryText:"La substance ou méthode est nécessaire au traitement d’une affection médicale dont le diagnostic est étayé par des preuves cliniques pertinentes.",evidence:"Le diagnostic est confirmé et accompagné de preuves cliniques pertinentes.",answer:"met"},
 {id:"performance",title:"Retour à l’état de santé normal",educationalText:"Le traitement ne doit pas améliorer la performance au-delà du retour à l’état de santé normal.",regulatoryText:"L’usage thérapeutique ne produit aucune amélioration autre que celle attribuable au retour à l’état de santé normal.",evidence:"Les données indiquent un retour à l’état de santé normal, sans avantage supplémentaire significatif.",answer:"met"},
 {id:"alternative",title:"Pas d’alternative autorisée raisonnable",educationalText:"Il n’existe pas d’autre solution autorisée et raisonnable pour traiter correctement le sportif.",regulatoryText:"La substance ou méthode est un traitement indiqué sans alternative thérapeutique autorisée et raisonnable.",evidence:"Le médecin n’a pas encore expliqué pourquoi une solution autorisée ne conviendrait pas.",answer:"missing"},
 {id:"prior-use",title:"Besoin non causé par un usage interdit antérieur",educationalText:"Le besoin actuel ne résulte pas d’un usage antérieur interdit réalisé sans AUT.",regulatoryText:"La nécessité n’est pas une conséquence partielle ou totale d’un usage antérieur sans AUT d’une substance ou méthode alors interdite.",evidence:"Le dossier établit que le besoin médical n’est pas la conséquence d’un usage interdit antérieur sans AUT.",answer:"met"}
];
export const TIMELINE=["Urgence médicale","Traitement nécessaire","Dossier médical","Demande d’AUT rétroactive","Examen par le comité","Décision"];
export const SOURCED_RULES={national:{educationalText:"Pour un sportif de niveau national, une AUT préalable est en principe nécessaire avant l’usage du traitement interdit.",source:REGULATORY_META.primarySource,lastChecked:REGULATORY_META.lastChecked},infranational:{educationalText:"Pour un sportif de niveau infranational, l’AUT préalable n’est pas obligatoire dans le régime présenté par l’AFLD ; une procédure rétroactive reste accessible, mais l’AUT n’est jamais automatique.",source:REGULATORY_META.primarySource,lastChecked:REGULATORY_META.lastChecked},retroactive:{educationalText:"L’urgence, certaines impossibilités exceptionnelles et le régime infranational peuvent permettre l’examen d’une demande rétroactive.",source:REGULATORY_META.primarySource,lastChecked:REGULATORY_META.lastChecked}};
export const shuffle=values=>[...values].sort(()=>Math.random()-.5);
