import { MOMENTS,PHASES,RIGHTS,RESPONSIBILITIES,FINAL_MESSAGE } from "../../droits-controle/situations.js";
const $=selector=>document.querySelector(selector),screens=["intro","moment","feedback","final"].map(id=>$("#"+id));let index=0,answers=[];
function show(screen){screens.forEach(item=>item.hidden=item!==screen);window.scrollTo({top:0,behavior:"smooth"})}
function list(container,items){container.replaceChildren(...items.map(text=>{const li=document.createElement("li");li.textContent=text;return li}))}
function discovered(type){return MOMENTS.slice(0,index).filter(item=>item.type===type).map(item=>item.reflex)}
function renderTimeline(phase){const current=PHASES.indexOf(phase);$("#timeline").replaceChildren(...PHASES.map((text,phaseIndex)=>{const span=document.createElement("span");span.textContent=text;if(phaseIndex<current)span.className="done";if(phaseIndex===current)span.className="current";return span}))}
function renderMoment(){const item=MOMENTS[index];renderTimeline(item.phase);$("#progress-label").textContent=`Moment clé ${index+1} sur ${MOMENTS.length}`;$("#phase-label").textContent=item.phase;$("#moment-title").textContent=item.title;$("#scene-text").textContent=item.scene;$("#question").textContent=item.question;$("#choices").replaceChildren(...item.choices.map((text,choice)=>{const label=document.createElement("label"),input=document.createElement("input");input.type="radio";input.name="choice";input.value=choice;label.append(input,document.createTextNode(text));return label}));list($("#rights-mini"),discovered("Droit"));list($("#responsibilities-mini"),discovered("Responsabilité"));$("#answer-message").textContent="";show($("#moment"))}
$("#answer-form").addEventListener("submit",event=>{event.preventDefault();const selected=new FormData(event.currentTarget).get("choice");if(selected===null){$("#answer-message").textContent="Choisis une réponse.";return}const item=MOMENTS[index],choice=Number(selected),correct=choice===item.correct;answers.push({id:item.id,choice,correct});window.ProcycleanGroup?.record("moment-"+index,item.question,item.choices[choice],item.choices[item.correct],item.feedback,correct);$("#feedback-result").textContent=correct?"Bon raisonnement":"À retenir";$("#feedback-result").className=`result ${correct?"correct":"learn"}`;$("#feedback-title").textContent=item.title;$("#feedback-text").textContent=item.feedback;$("#discovery-type").textContent=`${item.type.toUpperCase()} DÉCOUVERT${item.type==="Droit"?"":"E"}`;$("#discovery-reflex").textContent=item.reflex;(window.procycleanActivityStorage || localStorage).setItem("procyclean-solo-droits-controle",JSON.stringify({answers,current:index+1}));show($("#feedback"))});
function renderFinal(){list($("#final-rights"),RIGHTS);list($("#final-responsibilities"),RESPONSIBILITIES);$("#final-message").textContent=FINAL_MESSAGE;(window.procycleanActivityStorage || localStorage).setItem("procyclean-solo-droits-controle",JSON.stringify({answers,current:MOMENTS.length,completed:true}));show($("#final"))}
$("#continue").onclick=()=>{index+=1;if(index<MOMENTS.length)renderMoment();else renderFinal()};$("#start").onclick=renderMoment;$("#restart").onclick=()=>{index=0;answers=[];(window.procycleanActivityStorage || localStorage).removeItem("procyclean-solo-droits-controle");show($("#intro"))};
try{const saved=JSON.parse((window.procycleanActivityStorage || localStorage).getItem("procyclean-solo-droits-controle")||"null");if(saved&&Array.isArray(saved.answers)){answers=saved.answers;index=Math.min(Number(saved.current)||0,MOMENTS.length);if(saved.completed||index===MOMENTS.length)renderFinal();else if(index>0)renderMoment()}}catch(error){console.warn("Progression solo illisible, nouveau parcours.",error);(window.procycleanActivityStorage || localStorage).removeItem("procyclean-solo-droits-controle")}
const sceneImageObserver=new MutationObserver(()=>{const item=MOMENTS.find(moment=>moment.title===$("#moment-title").textContent);if(item){$("#scene-image").src=item.image;$("#scene-image").alt=`Illustration : ${item.title}`}});
sceneImageObserver.observe($("#moment-title"),{childList:true});
const feedbackObserver=new MutationObserver(()=>{const incorrect=$("#feedback-result").classList.contains("learn"),item=MOMENTS.find(moment=>moment.title===$("#feedback-title").textContent),label=incorrect?"Réponse incorrecte":"Bonne réponse";if($("#feedback-result").textContent!==label)$("#feedback-result").textContent=label;$("#expected-answer").hidden=!incorrect;$("#expected-answer").textContent=incorrect&&item?`La réponse attendue était : « ${item.choices[item.correct]} »`:""});
feedbackObserver.observe($("#feedback-result"),{childList:true});
const finalFeedbackObserver=new MutationObserver(()=>{const correct=answers.filter(answer=>answer.correct).length;$("#final-feedback").textContent=correct===MOMENTS.length?`Excellent : ${correct} bons raisonnements sur ${MOMENTS.length}. Tu as reconnu tous les bons réflexes.`:`Tu as reconnu ${correct} bons réflexes sur ${MOMENTS.length}. Ta fiche ci-dessous t’aide à consolider les situations à retenir.`});
finalFeedbackObserver.observe($("#final-message"),{childList:true});
if($("#final-message").textContent)$("#final-message").append(document.createTextNode(""));
document.documentElement.dataset.soloRightsReady="true";


// Synchronisation de ce même parcours lorsqu’il est ouvert dans une séance.
window.ProcycleanGroup?.register({
 snapshot:()=>({state:{answers,index},progress:answers.length/MOMENTS.length*100,complete:answers.length===MOMENTS.length}),
 restore:s=>{answers=s.answers||[];index=answers.length;if(index>=MOMENTS.length)renderFinal();else if(index)renderMoment();}
});
