import{QUESTIONS,answerRecord,answerLabel}from"../../labo-interdictions/quiz-data.js";
import{AFLD_URL,MEDICATION_EXERCISES,STATUS_OPTIONS,medicationAnswerRecord}from"../../labo-interdictions/medication-data.js";
const $=selector=>document.querySelector(selector),screens=["intro","quiz","final","step-two","medication","activity-final"].map(id=>$("#"+id)),storageKey="procyclean-interdictions-activity-v2";
let state={current:0,answers:[],completed:false,medicationIndex:0,medicationAnswers:[],stage2Completed:false},selected=null;
try{const saved=JSON.parse((window.procycleanActivityStorage || localStorage).getItem(storageKey));if(saved?.answers)state={...state,...saved}}catch{}
function save(){(window.procycleanActivityStorage || localStorage).setItem(storageKey,JSON.stringify(state))}
function show(screen){screens.forEach(item=>item.hidden=item!==screen);requestAnimationFrame(()=>screen.scrollIntoView({behavior:"smooth",block:"center",inline:"nearest"}))}
function renderQuestion(){const question=QUESTIONS[state.current],record=state.answers.find(item=>item.questionId===question.id);selected=record?.answer||null;$("#question-count").textContent="QUESTION "+(state.current+1)+" / "+QUESTIONS.length;$("#answered-count").textContent=state.answers.length+" réponse"+(state.answers.length>1?"s":"")+" enregistrée"+(state.answers.length>1?"s":"");$("#progress-bar").style.width=((state.current+1)/QUESTIONS.length*100)+"%";$("#situation").hidden=!question.situation;$("#situation").textContent=question.situation||"";$("#question").textContent=question.statement;$("#answers").replaceChildren(...question.answers.map(answer=>{const button=document.createElement("button");button.type="button";button.className="quiz-answer";button.textContent=answer.label;button.classList.toggle("selected",selected===answer.id);button.disabled=!!record;button.onclick=()=>{selected=answer.id;document.querySelectorAll("#answers .quiz-answer").forEach(item=>item.classList.toggle("selected",item===button));$("#validate").disabled=false};return button}));$("#validate").hidden=!!record;$("#validate").disabled=!selected;$("#feedback").hidden=!record;if(record)renderQuizFeedback(question,record);$("#next").textContent=state.current===QUESTIONS.length-1?"Voir la suite":"Question suivante";show($("#quiz"))}
function renderQuizFeedback(question,record){$("#feedback").className="quiz-feedback "+(record.correct?"correct":"rethink");$("#feedback-title").textContent=record.correct?"✓ Bonne réponse":"✗ Pas tout à fait";$("#feedback-text").textContent=record.correct?question.feedback:"La bonne réponse était « "+answerLabel(question,question.correct)+" ». "+question.feedback}
function renderMedication(){const exercise=MEDICATION_EXERCISES[state.medicationIndex],record=state.medicationAnswers.find(item=>item.medicationId===exercise.id);selected=record?.answer||null;$("#medication-level").textContent=exercise.level;$("#medication-count").textContent="RECHERCHE "+(state.medicationIndex+1)+" / "+MEDICATION_EXERCISES.length;$("#medication-progress").style.width=((state.medicationIndex+1)/MEDICATION_EXERCISES.length*100)+"%";$("#medication-name").textContent=exercise.name;$("#medication-instruction").textContent=exercise.instruction;$("#open-afld").href=AFLD_URL;$("#medication-options").replaceChildren(...STATUS_OPTIONS.map(option=>{const button=document.createElement("button");button.type="button";button.className="quiz-answer";button.textContent=option.label;button.classList.toggle("selected",selected===option.id);button.disabled=!!record;button.onclick=()=>{selected=option.id;document.querySelectorAll("#medication-options .quiz-answer").forEach(item=>item.classList.toggle("selected",item===button));$("#validate-medication").disabled=false};return button}));$("#validate-medication").hidden=!!record;$("#validate-medication").disabled=!selected;$("#medication-feedback").hidden=!record;if(record)renderMedicationFeedback(exercise,record);$("#next-medication").textContent=state.medicationIndex===MEDICATION_EXERCISES.length-1?"Terminer l’activité":"Recherche suivante";show($("#medication"))}
function renderMedicationFeedback(exercise,record){const expected=STATUS_OPTIONS.find(option=>option.id===exercise.expected)?.label;$("#medication-feedback").className="quiz-feedback "+(record.correct?"correct":"rethink");$("#medication-feedback-title").textContent=record.correct?"✓ Résultat bien lu":"✗ Pas tout à fait";$("#medication-feedback-text").textContent=record.correct?exercise.feedback:"Le statut à repérer était « "+expected+" ». "+exercise.feedback;$("#result-name").textContent=exercise.name;$("#result-route").textContent=exercise.route;$("#result-status").textContent=exercise.officialStatus;$("#result-active").textContent=exercise.activeIngredient}
$("#start").onclick=()=>state.stage2Completed?show($("#activity-final")):state.completed?show($("#final")):renderQuestion();
$("#validate").onclick=()=>{if(!selected)return;const question=QUESTIONS[state.current];state.answers.push(answerRecord(question,selected));window.ProcycleanGroup?.record("1-quiz-"+state.current,question.statement,answerLabel(question,selected),answerLabel(question,question.correct),question.feedback,selected===question.correct);save();renderQuestion()};
$("#next").onclick=()=>{if(state.current<QUESTIONS.length-1){state.current++;save();renderQuestion()}else{state.completed=true;save();show($("#final"))}};
$("#restart").onclick=()=>{state={current:0,answers:[],completed:false,medicationIndex:0,medicationAnswers:[],stage2Completed:false};selected=null;save();renderQuestion()};
$("#learn").onclick=()=>show($("#step-two"));
$("#begin-medications").onclick=()=>{state.medicationIndex=state.medicationAnswers.length>=MEDICATION_EXERCISES.length?0:state.medicationAnswers.length;save();renderMedication()};
$("#copy-name").onclick=async()=>{try{await navigator.clipboard.writeText(MEDICATION_EXERCISES[state.medicationIndex].name);$("#copy-name").textContent="Nom copié ✓"}catch{$("#copy-name").textContent="Sélectionne puis copie le nom"}};
$("#show-afld").onclick=()=>{$("#afld-embed").hidden=false;requestAnimationFrame(()=>$("#afld-embed").scrollIntoView({behavior:"smooth",block:"start"}))};
$("#hide-afld").onclick=()=>{$("#afld-embed").hidden=true;$("#show-afld").focus()};
let displayedMedication="";
new MutationObserver(()=>{const name=$("#medication-name").textContent;if(!name||name===displayedMedication)return;displayedMedication=name;$("#afld-embed").hidden=true;$("#copy-name").textContent="Copier le nom";const frame=$(".afld-embed iframe");frame.src="about:blank";requestAnimationFrame(()=>{frame.src=AFLD_URL})}).observe($("#medication-name"),{childList:true});
$("#validate-medication").onclick=()=>{if(!selected)return;const exercise=MEDICATION_EXERCISES[state.medicationIndex];state.medicationAnswers.push(medicationAnswerRecord(exercise,selected));window.ProcycleanGroup?.record("2-medicament-"+state.medicationIndex,exercise.name+" — "+exercise.instruction,STATUS_OPTIONS.find(x=>x.id===selected)?.label,STATUS_OPTIONS.find(x=>x.id===exercise.expected)?.label,exercise.feedback,selected===exercise.expected);save();renderMedication()};
$("#next-medication").onclick=()=>{if(state.medicationIndex<MEDICATION_EXERCISES.length-1){state.medicationIndex++;save();renderMedication()}else{state.stage2Completed=true;save();show($("#activity-final"))}};
$("#restart-all").onclick=()=>{state={current:0,answers:[],completed:false,medicationIndex:0,medicationAnswers:[],stage2Completed:false};selected=null;(window.procycleanActivityStorage || localStorage).removeItem(storageKey);show($("#intro"))};
document.addEventListener("click",event=>{const link=event.target.closest("a");if(!link)return;const destination=new URL(link.href,location.href).pathname.replace(/\\/g,"/");if(destination.endsWith("/activites/individuel/index.html")||destination.endsWith("/activites/index.html"))(window.procycleanActivityStorage || localStorage).removeItem(storageKey)},true);


// Synchronisation de ce même parcours lorsqu’il est ouvert dans une séance.
window.ProcycleanGroup?.register({
 snapshot:()=>({state:{data:state,screen:screens.find(x=>!x.hidden)?.id},progress:(state.answers.length+state.medicationAnswers.length)/(QUESTIONS.length+MEDICATION_EXERCISES.length)*100,complete:state.stage2Completed}),
 restore:s=>{state=s.data;const screen=s.screen;if(screen==="quiz")renderQuestion();else if(screen==="medication")renderMedication();else show($("#"+(screen||"intro")));}
});
